////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 2.4
//  \   \         Application : 7 Series FPGAs Transceivers Wizard 
//  /   /         Filename : ip_gtwizard_v2_4_1x_4ch_adapt_top_lpm.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1
module ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM #(
	parameter TIMER = 150
)
(
	input  EN,
	input  GTRXRESET,
	input  RXPMARESET,
	input  RXDFELPMRESET,
	//DRP
	input  DCLK,
	input  [15:0] DO,
	input  DRDY,
	output [8:0] DADDR,
	output [15:0] DI,
	output DEN,
	output DWE,
	output KLHOLD,
	output KHHOLD,
	//DONE	
	output DONE,
	//Debug
	output [53:0] DEBUG
);

wire rst = (GTRXRESET | RXPMARESET | RXDFELPMRESET) & EN;
wire start_done;
wire done_pre;
wire lock_done;
wire en_b;

//DRP-related
wire [8:0] daddr_starter;
wire den_starter;
wire dwe_starter;

wire [8:0] daddr_lock;
wire den_lock;
wire dwe_lock;
wire [15:0] di_lock;
wire [1:0] holds;
wire rst_lock;
reg lock_done_r, lock_done_r2;

//Debug signals
wire [4:0] lock_state;
wire [31:0] lock_count;
wire lock0, lock1, lock2, lock3;
wire [3:0] starter_state;
wire [2:0] starter_count;
wire starter_rst_int;
wire lock_done_rise;
wire [15:0] store_di0;
wire start, enable, kill0, kill1, kill2;

/////////////////////////////////////////////////////////////
assign en_b = ~EN;
assign rst_lock = ~start_done;
assign done_pre = lock_done;
assign DONE = done_pre & start_done; //So that DONE goes low immediately after any of RESET's is asserted

always @ (posedge DCLK)
begin
	lock_done_r <= lock_done;
	lock_done_r2 <= lock_done_r;
end

assign lock_done_rise = ~lock_done_r2 & lock_done_r;

assign DEBUG = {
	lock_state[4:0],//53:49
	lock_count[31:9],//48:26
	store_di0[15:0],//25:10
	lock0, lock1, lock2, lock3,//9:6
	start,enable,//5:4
	kill0,kill1,kill2,//3:1
	rst_lock//0
	};
assign KLHOLD = holds[0];
assign KHHOLD = holds[1];

//When a block is not active, it will hold DADDR,DI,DEN,DWE low
assign DADDR = en_b ? 9'd0 : (daddr_starter | daddr_lock);
assign DI    = en_b ? 16'd0 : (di_lock);
assign DEN   = en_b ? 1'b0 : (den_starter | den_lock);
assign DWE   = en_b ? 1'b0 : (dwe_starter | dwe_lock);

/***************************************
	Sequence of operation:
	-adapt_starter -> triggered by any of above resets to deassert then waits for DFE LPM reset to complete
	-agc_loop_fsm -> triggered by adapt_starter completion then waits for all loops to lock
***************************************/
ip_gtwizard_v2_4_1x_4ch_adapt_starter #(
	.WAIT_CYC(10)
) i_starter
(
	.RST(rst),
	.CLK(DCLK),
	.DO (DO),
	.DRDY(DRDY),
	.DADDR(daddr_starter),
	.DEN(den_starter),
	.DWE(dwe_starter),
	.READY(start_done),
	.curr_state_debug(starter_state[3:0]),
	.counter_debug(starter_count[2:0]),
	.rst_int_debug(starter_rst_int)
);

ip_gtwizard_v2_4_1x_4ch_lpm_loop_fsm #(
	.usr_clk(TIMER)
) i_lock (
	.DCLK(DCLK),
	.reset(rst_lock),
	.DRDY(DRDY),
	.D0(DO),
	.holds(holds), //KLHOLD,KHHOLD
	.DI(di_lock),
	.DADDR(daddr_lock),
	.DWE(dwe_lock),
	.DEN(den_lock),
	
	.kill3(lock_done),

	.state(lock_state[4:0]),
	.count_lock_out(lock_count[31:0]),
	.store_di0(store_di0),
	.start(start),
	.enable(enable),
	.kill0(kill0),
	.kill1(kill1),
	.kill2(kill2),
	.lock0(lock0),
	.lock1(lock1),
	.lock2(lock2),
	.lock3(lock3)
);

endmodule


