//------------------------------------------------------------------------------
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 2.4
//  \   \         Application : 7 Series FPGAs Transceivers Wizard 
//  /   /         Filename : ip_gtwizard_v2_4_1x_4ch_init.v
// /___/   /\      
// \   \  /  \ 
//  \___\/\___\
//
//  Description : This module instantiates the modules required for
//                reset and initialisation of the Transceiver
//
// Module ip_gtwizard_v2_4_1x_4ch_init
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1

//***********************************Entity Declaration************************

module ip_gtwizard_v2_4_1x_4ch_init #
(
    parameter EXAMPLE_SIM_GTRESET_SPEEDUP            = "TRUE",     // Simulation setting for GT SecureIP model
    parameter EXAMPLE_SIMULATION                     =  0,         // Set to 1 for simulation
    parameter EQ_MODE                                =  "DFE",         // Rx Equalization Mode - Set to DFE or LPM
    parameter EXAMPLE_USE_CHIPSCOPE                  =  0          // Set to 1 to use Chipscope to drive resets

)
(
    input           SYSCLK_IN,
    input           SOFT_RESET_IN,
    output          GT0_TX_FSM_RESET_DONE_OUT,
    output          GT0_RX_FSM_RESET_DONE_OUT,
    input           GT0_DATA_VALID_IN,
    output          GT1_TX_FSM_RESET_DONE_OUT,
    output          GT1_RX_FSM_RESET_DONE_OUT,
    input           GT1_DATA_VALID_IN,
    output          GT2_TX_FSM_RESET_DONE_OUT,
    output          GT2_RX_FSM_RESET_DONE_OUT,
    input           GT2_DATA_VALID_IN,
    output          GT3_TX_FSM_RESET_DONE_OUT,
    output          GT3_RX_FSM_RESET_DONE_OUT,
    input           GT3_DATA_VALID_IN,

    //_________________________________________________________________________
    //GT0  (X1Y8)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT0_DRPADDR_IN,
    input           GT0_DRPCLK_IN,
    input   [15:0]  GT0_DRPDI_IN,
    output  [15:0]  GT0_DRPDO_OUT,
    input           GT0_DRPEN_IN,
    output          GT0_DRPRDY_OUT,
    input           GT0_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT0_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT0_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT0_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT0_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT0_RXUSRCLK_IN,
    input           GT0_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT0_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT0_RXPRBSERR_OUT,
    input   [2:0]   GT0_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT0_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT0_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT0_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT0_RXBUFRESET_IN,
    output  [2:0]   GT0_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT0_RXDFELPMRESET_IN,
    output  [6:0]   GT0_RXMONITOROUT_OUT,
    input   [1:0]   GT0_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT0_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT0_RXDATAVALID_OUT,
    output  [1:0]   GT0_RXHEADER_OUT,
    output          GT0_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT0_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT0_GTRXRESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT0_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT0_GTTXRESET_IN,
    input           GT0_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT0_TXUSRCLK_IN,
    input           GT0_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT0_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT0_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT0_GTXTXN_OUT,
    output          GT0_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT0_TXOUTCLK_OUT,
    output          GT0_TXOUTCLKFABRIC_OUT,
    output          GT0_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT0_TXHEADER_IN,
    input   [6:0]   GT0_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          GT0_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT0_TXPRBSSEL_IN,

    //GT1  (X1Y9)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT1_DRPADDR_IN,
    input           GT1_DRPCLK_IN,
    input   [15:0]  GT1_DRPDI_IN,
    output  [15:0]  GT1_DRPDO_OUT,
    input           GT1_DRPEN_IN,
    output          GT1_DRPRDY_OUT,
    input           GT1_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT1_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT1_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT1_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT1_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT1_RXUSRCLK_IN,
    input           GT1_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT1_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT1_RXPRBSERR_OUT,
    input   [2:0]   GT1_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT1_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT1_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT1_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT1_RXBUFRESET_IN,
    output  [2:0]   GT1_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT1_RXDFELPMRESET_IN,
    output  [6:0]   GT1_RXMONITOROUT_OUT,
    input   [1:0]   GT1_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT1_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT1_RXDATAVALID_OUT,
    output  [1:0]   GT1_RXHEADER_OUT,
    output          GT1_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT1_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT1_GTRXRESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT1_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT1_GTTXRESET_IN,
    input           GT1_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT1_TXUSRCLK_IN,
    input           GT1_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT1_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT1_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT1_GTXTXN_OUT,
    output          GT1_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT1_TXOUTCLK_OUT,
    output          GT1_TXOUTCLKFABRIC_OUT,
    output          GT1_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT1_TXHEADER_IN,
    input   [6:0]   GT1_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          GT1_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT1_TXPRBSSEL_IN,

    //GT2  (X1Y10)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT2_DRPADDR_IN,
    input           GT2_DRPCLK_IN,
    input   [15:0]  GT2_DRPDI_IN,
    output  [15:0]  GT2_DRPDO_OUT,
    input           GT2_DRPEN_IN,
    output          GT2_DRPRDY_OUT,
    input           GT2_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT2_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT2_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT2_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT2_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT2_RXUSRCLK_IN,
    input           GT2_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT2_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT2_RXPRBSERR_OUT,
    input   [2:0]   GT2_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT2_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT2_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT2_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT2_RXBUFRESET_IN,
    output  [2:0]   GT2_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT2_RXDFELPMRESET_IN,
    output  [6:0]   GT2_RXMONITOROUT_OUT,
    input   [1:0]   GT2_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT2_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT2_RXDATAVALID_OUT,
    output  [1:0]   GT2_RXHEADER_OUT,
    output          GT2_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT2_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT2_GTRXRESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT2_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT2_GTTXRESET_IN,
    input           GT2_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT2_TXUSRCLK_IN,
    input           GT2_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT2_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT2_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT2_GTXTXN_OUT,
    output          GT2_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT2_TXOUTCLK_OUT,
    output          GT2_TXOUTCLKFABRIC_OUT,
    output          GT2_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT2_TXHEADER_IN,
    input   [6:0]   GT2_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          GT2_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT2_TXPRBSSEL_IN,

    //GT3  (X1Y11)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT3_DRPADDR_IN,
    input           GT3_DRPCLK_IN,
    input   [15:0]  GT3_DRPDI_IN,
    output  [15:0]  GT3_DRPDO_OUT,
    input           GT3_DRPEN_IN,
    output          GT3_DRPRDY_OUT,
    input           GT3_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT3_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT3_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT3_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT3_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT3_RXUSRCLK_IN,
    input           GT3_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT3_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT3_RXPRBSERR_OUT,
    input   [2:0]   GT3_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT3_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT3_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT3_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT3_RXBUFRESET_IN,
    output  [2:0]   GT3_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT3_RXDFELPMRESET_IN,
    output  [6:0]   GT3_RXMONITOROUT_OUT,
    input   [1:0]   GT3_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT3_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT3_RXDATAVALID_OUT,
    output  [1:0]   GT3_RXHEADER_OUT,
    output          GT3_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT3_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT3_GTRXRESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT3_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT3_GTTXRESET_IN,
    input           GT3_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT3_TXUSRCLK_IN,
    input           GT3_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT3_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT3_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT3_GTXTXN_OUT,
    output          GT3_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT3_TXOUTCLK_OUT,
    output          GT3_TXOUTCLKFABRIC_OUT,
    output          GT3_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT3_TXHEADER_IN,
    input   [6:0]   GT3_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          GT3_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT3_TXPRBSSEL_IN,


    //____________________________COMMON PORTS________________________________
    //-------------------- Common Block  - Ref Clock Ports ---------------------
    input           GT0_GTREFCLK0_COMMON_IN,
    //----------------------- Common Block - QPLL Ports ------------------------
    output          GT0_QPLLLOCK_OUT,
    input           GT0_QPLLLOCKDETCLK_IN,
    input           GT0_QPLLRESET_IN


);



//***********************************Parameter Declarations********************

    parameter STABLE_CLOCK_PERIOD  = 20;               //Period of the stable clock driving this state-machine, unit is [ns]

    //Typical CDRLOCK Time is 50,000UI, as per DS183
    parameter RX_CDRLOCK_TIME      = (EXAMPLE_SIMULATION == 1) ? 1000 : 50000/10;

    parameter integer LPM_ADAPT_LOCK_TIMER = (EXAMPLE_SIMULATION == 1) ? 5 : (13*100)/10;

    parameter integer DFE_ADAPT_LOCK_TIMER = (13*100)/10;
       
    integer   WAIT_TIME_CDRLOCK    = RX_CDRLOCK_TIME / STABLE_CLOCK_PERIOD;      

//-------------------------- GT Wrapper Wires ------------------------------
    wire           gt0_txresetdone_i;
    wire           gt0_rxresetdone_i;
    wire           gt0_gttxreset_i;
    wire           gt0_gttxreset_t;
    wire           gt0_gtrxreset_i;
    wire           gt0_gtrxreset_t;
    wire           gt0_txpcsreset_i;
    wire           gt0_rxpcsreset_i;
    wire           gt0_rxpmareset_i;
    wire           gt0_rxdfelpmreset_i;
    wire           gt0_txuserrdy_i;
    wire           gt0_txuserrdy_t;
    wire           gt0_rxuserrdy_i;
    wire           gt0_rxuserrdy_t;

    wire           gt0_rxdfeagchold_i;
    wire           gt0_rxdfelfhold_i;
    wire           gt0_rxlpmlfhold_i;
    wire           gt0_rxlpmhfhold_i;

    wire   [8:0]   gt0_drpaddr_i;
    wire   [15:0]  gt0_drpdi_i;
    wire   [15:0]  gt0_drpdo_o;
    wire           gt0_drpen_i;
    wire           gt0_drpwe_i;
    wire           gt0_drprdy_o;

    wire   [8:0]   gt0_drpaddr_int;
    wire   [15:0]  gt0_drpdi_int;
    wire   [15:0]  gt0_drpdo_int;
    wire           gt0_drpen_int;
    wire           gt0_drpwe_int;
    wire           gt0_drprdy_int;
    
    wire   [6:0]   gt0_rxmonitorout_o;
    wire   [1:0]   gt0_rxmonitorsel_i;
    wire           gt0_adapt_done;

    wire           gt1_txresetdone_i;
    wire           gt1_rxresetdone_i;
    wire           gt1_gttxreset_i;
    wire           gt1_gttxreset_t;
    wire           gt1_gtrxreset_i;
    wire           gt1_gtrxreset_t;
    wire           gt1_txpcsreset_i;
    wire           gt1_rxpcsreset_i;
    wire           gt1_rxpmareset_i;
    wire           gt1_rxdfelpmreset_i;
    wire           gt1_txuserrdy_i;
    wire           gt1_txuserrdy_t;
    wire           gt1_rxuserrdy_i;
    wire           gt1_rxuserrdy_t;

    wire           gt1_rxdfeagchold_i;
    wire           gt1_rxdfelfhold_i;
    wire           gt1_rxlpmlfhold_i;
    wire           gt1_rxlpmhfhold_i;

    wire   [8:0]   gt1_drpaddr_i;
    wire   [15:0]  gt1_drpdi_i;
    wire   [15:0]  gt1_drpdo_o;
    wire           gt1_drpen_i;
    wire           gt1_drpwe_i;
    wire           gt1_drprdy_o;

    wire   [8:0]   gt1_drpaddr_int;
    wire   [15:0]  gt1_drpdi_int;
    wire   [15:0]  gt1_drpdo_int;
    wire           gt1_drpen_int;
    wire           gt1_drpwe_int;
    wire           gt1_drprdy_int;
    
    wire   [6:0]   gt1_rxmonitorout_o;
    wire   [1:0]   gt1_rxmonitorsel_i;
    wire           gt1_adapt_done;

    wire           gt2_txresetdone_i;
    wire           gt2_rxresetdone_i;
    wire           gt2_gttxreset_i;
    wire           gt2_gttxreset_t;
    wire           gt2_gtrxreset_i;
    wire           gt2_gtrxreset_t;
    wire           gt2_txpcsreset_i;
    wire           gt2_rxpcsreset_i;
    wire           gt2_rxpmareset_i;
    wire           gt2_rxdfelpmreset_i;
    wire           gt2_txuserrdy_i;
    wire           gt2_txuserrdy_t;
    wire           gt2_rxuserrdy_i;
    wire           gt2_rxuserrdy_t;

    wire           gt2_rxdfeagchold_i;
    wire           gt2_rxdfelfhold_i;
    wire           gt2_rxlpmlfhold_i;
    wire           gt2_rxlpmhfhold_i;

    wire   [8:0]   gt2_drpaddr_i;
    wire   [15:0]  gt2_drpdi_i;
    wire   [15:0]  gt2_drpdo_o;
    wire           gt2_drpen_i;
    wire           gt2_drpwe_i;
    wire           gt2_drprdy_o;

    wire   [8:0]   gt2_drpaddr_int;
    wire   [15:0]  gt2_drpdi_int;
    wire   [15:0]  gt2_drpdo_int;
    wire           gt2_drpen_int;
    wire           gt2_drpwe_int;
    wire           gt2_drprdy_int;
    
    wire   [6:0]   gt2_rxmonitorout_o;
    wire   [1:0]   gt2_rxmonitorsel_i;
    wire           gt2_adapt_done;

    wire           gt3_txresetdone_i;
    wire           gt3_rxresetdone_i;
    wire           gt3_gttxreset_i;
    wire           gt3_gttxreset_t;
    wire           gt3_gtrxreset_i;
    wire           gt3_gtrxreset_t;
    wire           gt3_txpcsreset_i;
    wire           gt3_rxpcsreset_i;
    wire           gt3_rxpmareset_i;
    wire           gt3_rxdfelpmreset_i;
    wire           gt3_txuserrdy_i;
    wire           gt3_txuserrdy_t;
    wire           gt3_rxuserrdy_i;
    wire           gt3_rxuserrdy_t;

    wire           gt3_rxdfeagchold_i;
    wire           gt3_rxdfelfhold_i;
    wire           gt3_rxlpmlfhold_i;
    wire           gt3_rxlpmhfhold_i;

    wire   [8:0]   gt3_drpaddr_i;
    wire   [15:0]  gt3_drpdi_i;
    wire   [15:0]  gt3_drpdo_o;
    wire           gt3_drpen_i;
    wire           gt3_drpwe_i;
    wire           gt3_drprdy_o;

    wire   [8:0]   gt3_drpaddr_int;
    wire   [15:0]  gt3_drpdi_int;
    wire   [15:0]  gt3_drpdo_int;
    wire           gt3_drpen_int;
    wire           gt3_drpwe_int;
    wire           gt3_drprdy_int;
    
    wire   [6:0]   gt3_rxmonitorout_o;
    wire   [1:0]   gt3_rxmonitorsel_i;
    wire           gt3_adapt_done;


    wire           gt0_qpllreset_i;
    wire           gt0_qpllreset_t;
    wire           gt0_qpllrefclklost_i;
    wire           gt0_qplllock_i;


//------------------------------- Global Signals -----------------------------
    wire           tied_to_ground_i;
    wire           tied_to_vcc_i;

    wire           gt0_rxoutclk_i;
    wire           gt0_recclk_stable_i;

    wire           gt1_rxoutclk_i;
    wire           gt1_recclk_stable_i;

    wire           gt2_rxoutclk_i;
    wire           gt2_recclk_stable_i;

    wire           gt3_rxoutclk_i;
    wire           gt3_recclk_stable_i;







    integer  rx_cdrlock_counter= 0;
    reg              rx_cdrlocked;


 


//**************************** Main Body of Code *******************************
    //  Static signal Assigments
    assign  tied_to_ground_i                     =  1'b0;
    assign  tied_to_vcc_i                        =  1'b1;

//    ----------------------------- The GT Wrapper -----------------------------
    
    // Use the instantiation template in the example directory to add the GT wrapper to your design.
    // In this example, the wrapper is wired up for basic operation with a frame generator and frame 
    // checker. The GTs will reset, then attempt to align and transmit data. If channel bonding is 
    // enabled, bonding should occur after alignment.


    ip_gtwizard_v2_4_1x_4ch #
    (
        .WRAPPER_SIM_GTRESET_SPEEDUP    (EXAMPLE_SIM_GTRESET_SPEEDUP)
    )
    ip_gtwizard_v2_4_1x_4ch_i
    (
  
        //_____________________________________________________________________
        //_____________________________________________________________________
        //GT0  (X1Y8)

        //-------------------------- Channel - DRP Ports  --------------------------
        .GT0_DRPADDR_IN                 (gt0_drpaddr_i),
        .GT0_DRPCLK_IN                  (GT0_DRPCLK_IN),
        .GT0_DRPDI_IN                   (gt0_drpdi_i),
        .GT0_DRPDO_OUT                  (gt0_drpdo_o),
        .GT0_DRPEN_IN                   (gt0_drpen_i),
        .GT0_DRPRDY_OUT                 (gt0_drprdy_o),
        .GT0_DRPWE_IN                   (gt0_drpwe_i),
        //----------------------------- Loopback Ports -----------------------------
        .GT0_LOOPBACK_IN                (GT0_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .GT0_RXUSERRDY_IN               (gt0_rxuserrdy_i),
        //------------------------ RX Margin Analysis Ports ------------------------
        .GT0_EYESCANDATAERROR_OUT       (GT0_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .GT0_RXCDRLOCK_OUT              (GT0_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .GT0_RXUSRCLK_IN                (GT0_RXUSRCLK_IN),
        .GT0_RXUSRCLK2_IN               (GT0_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .GT0_RXDATA_OUT                 (GT0_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .GT0_RXPRBSERR_OUT              (GT0_RXPRBSERR_OUT),
        .GT0_RXPRBSSEL_IN               (GT0_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .GT0_RXPRBSCNTRESET_IN          (GT0_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GT0_GTXRXP_IN                  (GT0_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GT0_GTXRXN_IN                  (GT0_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .GT0_RXBUFRESET_IN              (GT0_RXBUFRESET_IN),
        .GT0_RXBUFSTATUS_OUT            (GT0_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .GT0_RXDFEAGCHOLD_IN            (gt0_rxdfeagchold_i),
        .GT0_RXDFELPMRESET_IN           (gt0_rxdfelpmreset_i),
        .GT0_RXMONITOROUT_OUT           (gt0_rxmonitorout_o),
        .GT0_RXMONITORSEL_IN            (gt0_rxmonitorsel_i),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .GT0_RXOUTCLK_OUT               (gt0_rxoutclk_i),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .GT0_RXDATAVALID_OUT            (GT0_RXDATAVALID_OUT),
        .GT0_RXHEADER_OUT               (GT0_RXHEADER_OUT),
        .GT0_RXHEADERVALID_OUT          (GT0_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .GT0_RXGEARBOXSLIP_IN           (GT0_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GT0_GTRXRESET_IN               (gt0_gtrxreset_i),
        .GT0_RXPCSRESET_IN              (gt0_rxpcsreset_i),
        .GT0_RXPMARESET_IN              (gt0_rxpmareset_i),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .GT0_RXRESETDONE_OUT            (gt0_rxresetdone_i),
        //------------------- TX Initialization and Reset Ports --------------------
        .GT0_GTTXRESET_IN               (gt0_gttxreset_i),
        .GT0_TXUSERRDY_IN               (gt0_txuserrdy_i),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .GT0_TXUSRCLK_IN                (GT0_TXUSRCLK_IN),
        .GT0_TXUSRCLK2_IN               (GT0_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .GT0_TXELECIDLE_IN              (GT0_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GT0_TXDATA_IN                  (GT0_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GT0_GTXTXN_OUT                 (GT0_GTXTXN_OUT),
        .GT0_GTXTXP_OUT                 (GT0_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .GT0_TXOUTCLK_OUT               (GT0_TXOUTCLK_OUT),
        .GT0_TXOUTCLKFABRIC_OUT         (GT0_TXOUTCLKFABRIC_OUT),
        .GT0_TXOUTCLKPCS_OUT            (GT0_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .GT0_TXHEADER_IN                (GT0_TXHEADER_IN),
        .GT0_TXSEQUENCE_IN              (GT0_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .GT0_TXPCSRESET_IN              (gt0_txpcsreset_i),
        .GT0_TXRESETDONE_OUT            (gt0_txresetdone_i),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .GT0_TXPRBSSEL_IN               (GT0_TXPRBSSEL_IN),


  
        //_____________________________________________________________________
        //_____________________________________________________________________
        //GT1  (X1Y9)

        //-------------------------- Channel - DRP Ports  --------------------------
        .GT1_DRPADDR_IN                 (gt1_drpaddr_i),
        .GT1_DRPCLK_IN                  (GT1_DRPCLK_IN),
        .GT1_DRPDI_IN                   (gt1_drpdi_i),
        .GT1_DRPDO_OUT                  (gt1_drpdo_o),
        .GT1_DRPEN_IN                   (gt1_drpen_i),
        .GT1_DRPRDY_OUT                 (gt1_drprdy_o),
        .GT1_DRPWE_IN                   (gt1_drpwe_i),
        //----------------------------- Loopback Ports -----------------------------
        .GT1_LOOPBACK_IN                (GT1_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .GT1_RXUSERRDY_IN               (gt1_rxuserrdy_i),
        //------------------------ RX Margin Analysis Ports ------------------------
        .GT1_EYESCANDATAERROR_OUT       (GT1_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .GT1_RXCDRLOCK_OUT              (GT1_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .GT1_RXUSRCLK_IN                (GT1_RXUSRCLK_IN),
        .GT1_RXUSRCLK2_IN               (GT1_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .GT1_RXDATA_OUT                 (GT1_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .GT1_RXPRBSERR_OUT              (GT1_RXPRBSERR_OUT),
        .GT1_RXPRBSSEL_IN               (GT1_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .GT1_RXPRBSCNTRESET_IN          (GT1_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GT1_GTXRXP_IN                  (GT1_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GT1_GTXRXN_IN                  (GT1_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .GT1_RXBUFRESET_IN              (GT1_RXBUFRESET_IN),
        .GT1_RXBUFSTATUS_OUT            (GT1_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .GT1_RXDFEAGCHOLD_IN            (gt1_rxdfeagchold_i),
        .GT1_RXDFELPMRESET_IN           (gt1_rxdfelpmreset_i),
        .GT1_RXMONITOROUT_OUT           (gt1_rxmonitorout_o),
        .GT1_RXMONITORSEL_IN            (gt1_rxmonitorsel_i),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .GT1_RXOUTCLK_OUT               (gt1_rxoutclk_i),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .GT1_RXDATAVALID_OUT            (GT1_RXDATAVALID_OUT),
        .GT1_RXHEADER_OUT               (GT1_RXHEADER_OUT),
        .GT1_RXHEADERVALID_OUT          (GT1_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .GT1_RXGEARBOXSLIP_IN           (GT1_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GT1_GTRXRESET_IN               (gt1_gtrxreset_i),
        .GT1_RXPCSRESET_IN              (gt1_rxpcsreset_i),
        .GT1_RXPMARESET_IN              (gt1_rxpmareset_i),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .GT1_RXRESETDONE_OUT            (gt1_rxresetdone_i),
        //------------------- TX Initialization and Reset Ports --------------------
        .GT1_GTTXRESET_IN               (gt1_gttxreset_i),
        .GT1_TXUSERRDY_IN               (gt1_txuserrdy_i),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .GT1_TXUSRCLK_IN                (GT1_TXUSRCLK_IN),
        .GT1_TXUSRCLK2_IN               (GT1_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .GT1_TXELECIDLE_IN              (GT1_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GT1_TXDATA_IN                  (GT1_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GT1_GTXTXN_OUT                 (GT1_GTXTXN_OUT),
        .GT1_GTXTXP_OUT                 (GT1_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .GT1_TXOUTCLK_OUT               (GT1_TXOUTCLK_OUT),
        .GT1_TXOUTCLKFABRIC_OUT         (GT1_TXOUTCLKFABRIC_OUT),
        .GT1_TXOUTCLKPCS_OUT            (GT1_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .GT1_TXHEADER_IN                (GT1_TXHEADER_IN),
        .GT1_TXSEQUENCE_IN              (GT1_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .GT1_TXPCSRESET_IN              (gt1_txpcsreset_i),
        .GT1_TXRESETDONE_OUT            (gt1_txresetdone_i),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .GT1_TXPRBSSEL_IN               (GT1_TXPRBSSEL_IN),


  
        //_____________________________________________________________________
        //_____________________________________________________________________
        //GT2  (X1Y10)

        //-------------------------- Channel - DRP Ports  --------------------------
        .GT2_DRPADDR_IN                 (gt2_drpaddr_i),
        .GT2_DRPCLK_IN                  (GT2_DRPCLK_IN),
        .GT2_DRPDI_IN                   (gt2_drpdi_i),
        .GT2_DRPDO_OUT                  (gt2_drpdo_o),
        .GT2_DRPEN_IN                   (gt2_drpen_i),
        .GT2_DRPRDY_OUT                 (gt2_drprdy_o),
        .GT2_DRPWE_IN                   (gt2_drpwe_i),
        //----------------------------- Loopback Ports -----------------------------
        .GT2_LOOPBACK_IN                (GT2_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .GT2_RXUSERRDY_IN               (gt2_rxuserrdy_i),
        //------------------------ RX Margin Analysis Ports ------------------------
        .GT2_EYESCANDATAERROR_OUT       (GT2_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .GT2_RXCDRLOCK_OUT              (GT2_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .GT2_RXUSRCLK_IN                (GT2_RXUSRCLK_IN),
        .GT2_RXUSRCLK2_IN               (GT2_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .GT2_RXDATA_OUT                 (GT2_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .GT2_RXPRBSERR_OUT              (GT2_RXPRBSERR_OUT),
        .GT2_RXPRBSSEL_IN               (GT2_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .GT2_RXPRBSCNTRESET_IN          (GT2_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GT2_GTXRXP_IN                  (GT2_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GT2_GTXRXN_IN                  (GT2_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .GT2_RXBUFRESET_IN              (GT2_RXBUFRESET_IN),
        .GT2_RXBUFSTATUS_OUT            (GT2_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .GT2_RXDFEAGCHOLD_IN            (gt2_rxdfeagchold_i),
        .GT2_RXDFELPMRESET_IN           (gt2_rxdfelpmreset_i),
        .GT2_RXMONITOROUT_OUT           (gt2_rxmonitorout_o),
        .GT2_RXMONITORSEL_IN            (gt2_rxmonitorsel_i),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .GT2_RXOUTCLK_OUT               (gt2_rxoutclk_i),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .GT2_RXDATAVALID_OUT            (GT2_RXDATAVALID_OUT),
        .GT2_RXHEADER_OUT               (GT2_RXHEADER_OUT),
        .GT2_RXHEADERVALID_OUT          (GT2_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .GT2_RXGEARBOXSLIP_IN           (GT2_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GT2_GTRXRESET_IN               (gt2_gtrxreset_i),
        .GT2_RXPCSRESET_IN              (gt2_rxpcsreset_i),
        .GT2_RXPMARESET_IN              (gt2_rxpmareset_i),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .GT2_RXRESETDONE_OUT            (gt2_rxresetdone_i),
        //------------------- TX Initialization and Reset Ports --------------------
        .GT2_GTTXRESET_IN               (gt2_gttxreset_i),
        .GT2_TXUSERRDY_IN               (gt2_txuserrdy_i),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .GT2_TXUSRCLK_IN                (GT2_TXUSRCLK_IN),
        .GT2_TXUSRCLK2_IN               (GT2_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .GT2_TXELECIDLE_IN              (GT2_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GT2_TXDATA_IN                  (GT2_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GT2_GTXTXN_OUT                 (GT2_GTXTXN_OUT),
        .GT2_GTXTXP_OUT                 (GT2_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .GT2_TXOUTCLK_OUT               (GT2_TXOUTCLK_OUT),
        .GT2_TXOUTCLKFABRIC_OUT         (GT2_TXOUTCLKFABRIC_OUT),
        .GT2_TXOUTCLKPCS_OUT            (GT2_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .GT2_TXHEADER_IN                (GT2_TXHEADER_IN),
        .GT2_TXSEQUENCE_IN              (GT2_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .GT2_TXPCSRESET_IN              (gt2_txpcsreset_i),
        .GT2_TXRESETDONE_OUT            (gt2_txresetdone_i),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .GT2_TXPRBSSEL_IN               (GT2_TXPRBSSEL_IN),


  
        //_____________________________________________________________________
        //_____________________________________________________________________
        //GT3  (X1Y11)

        //-------------------------- Channel - DRP Ports  --------------------------
        .GT3_DRPADDR_IN                 (gt3_drpaddr_i),
        .GT3_DRPCLK_IN                  (GT3_DRPCLK_IN),
        .GT3_DRPDI_IN                   (gt3_drpdi_i),
        .GT3_DRPDO_OUT                  (gt3_drpdo_o),
        .GT3_DRPEN_IN                   (gt3_drpen_i),
        .GT3_DRPRDY_OUT                 (gt3_drprdy_o),
        .GT3_DRPWE_IN                   (gt3_drpwe_i),
        //----------------------------- Loopback Ports -----------------------------
        .GT3_LOOPBACK_IN                (GT3_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .GT3_RXUSERRDY_IN               (gt3_rxuserrdy_i),
        //------------------------ RX Margin Analysis Ports ------------------------
        .GT3_EYESCANDATAERROR_OUT       (GT3_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .GT3_RXCDRLOCK_OUT              (GT3_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .GT3_RXUSRCLK_IN                (GT3_RXUSRCLK_IN),
        .GT3_RXUSRCLK2_IN               (GT3_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .GT3_RXDATA_OUT                 (GT3_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .GT3_RXPRBSERR_OUT              (GT3_RXPRBSERR_OUT),
        .GT3_RXPRBSSEL_IN               (GT3_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .GT3_RXPRBSCNTRESET_IN          (GT3_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GT3_GTXRXP_IN                  (GT3_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GT3_GTXRXN_IN                  (GT3_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .GT3_RXBUFRESET_IN              (GT3_RXBUFRESET_IN),
        .GT3_RXBUFSTATUS_OUT            (GT3_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .GT3_RXDFEAGCHOLD_IN            (gt3_rxdfeagchold_i),
        .GT3_RXDFELPMRESET_IN           (gt3_rxdfelpmreset_i),
        .GT3_RXMONITOROUT_OUT           (gt3_rxmonitorout_o),
        .GT3_RXMONITORSEL_IN            (gt3_rxmonitorsel_i),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .GT3_RXOUTCLK_OUT               (gt3_rxoutclk_i),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .GT3_RXDATAVALID_OUT            (GT3_RXDATAVALID_OUT),
        .GT3_RXHEADER_OUT               (GT3_RXHEADER_OUT),
        .GT3_RXHEADERVALID_OUT          (GT3_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .GT3_RXGEARBOXSLIP_IN           (GT3_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GT3_GTRXRESET_IN               (gt3_gtrxreset_i),
        .GT3_RXPCSRESET_IN              (gt3_rxpcsreset_i),
        .GT3_RXPMARESET_IN              (gt3_rxpmareset_i),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .GT3_RXRESETDONE_OUT            (gt3_rxresetdone_i),
        //------------------- TX Initialization and Reset Ports --------------------
        .GT3_GTTXRESET_IN               (gt3_gttxreset_i),
        .GT3_TXUSERRDY_IN               (gt3_txuserrdy_i),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .GT3_TXUSRCLK_IN                (GT3_TXUSRCLK_IN),
        .GT3_TXUSRCLK2_IN               (GT3_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .GT3_TXELECIDLE_IN              (GT3_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GT3_TXDATA_IN                  (GT3_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GT3_GTXTXN_OUT                 (GT3_GTXTXN_OUT),
        .GT3_GTXTXP_OUT                 (GT3_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .GT3_TXOUTCLK_OUT               (GT3_TXOUTCLK_OUT),
        .GT3_TXOUTCLKFABRIC_OUT         (GT3_TXOUTCLKFABRIC_OUT),
        .GT3_TXOUTCLKPCS_OUT            (GT3_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .GT3_TXHEADER_IN                (GT3_TXHEADER_IN),
        .GT3_TXSEQUENCE_IN              (GT3_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .GT3_TXPCSRESET_IN              (gt3_txpcsreset_i),
        .GT3_TXRESETDONE_OUT            (gt3_txresetdone_i),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .GT3_TXPRBSSEL_IN               (GT3_TXPRBSSEL_IN),




    //____________________________COMMON PORTS________________________________
        //-------------------- Common Block  - Ref Clock Ports ---------------------
        .GT0_GTREFCLK0_COMMON_IN        (GT0_GTREFCLK0_COMMON_IN),
        //----------------------- Common Block - QPLL Ports ------------------------
        .GT0_QPLLLOCK_OUT               (gt0_qplllock_i),
        .GT0_QPLLLOCKDETCLK_IN          (GT0_QPLLLOCKDETCLK_IN),
        .GT0_QPLLREFCLKLOST_OUT         (gt0_qpllrefclklost_i),
        .GT0_QPLLRESET_IN               (gt0_qpllreset_i)

    );

    assign  gt0_rxpcsreset_i                     =  tied_to_ground_i;
    assign  gt0_txpcsreset_i                     =  tied_to_ground_i;
    assign  gt1_rxpcsreset_i                     =  tied_to_ground_i;
    assign  gt1_txpcsreset_i                     =  tied_to_ground_i;
    assign  gt2_rxpcsreset_i                     =  tied_to_ground_i;
    assign  gt2_txpcsreset_i                     =  tied_to_ground_i;
    assign  gt3_rxpcsreset_i                     =  tied_to_ground_i;
    assign  gt3_txpcsreset_i                     =  tied_to_ground_i;

    assign  gt0_rxpmareset_i                     =  tied_to_ground_i;
    assign  gt0_rxdfelpmreset_i                  =  tied_to_ground_i;
    assign  gt1_rxpmareset_i                     =  tied_to_ground_i;
    assign  gt1_rxdfelpmreset_i                  =  tied_to_ground_i;
    assign  gt2_rxpmareset_i                     =  tied_to_ground_i;
    assign  gt2_rxdfelpmreset_i                  =  tied_to_ground_i;
    assign  gt3_rxpmareset_i                     =  tied_to_ground_i;
    assign  gt3_rxdfelpmreset_i                  =  tied_to_ground_i;


    assign  GT0_TXRESETDONE_OUT                  =  gt0_txresetdone_i;
    assign  GT0_RXRESETDONE_OUT                  =  gt0_rxresetdone_i;
    assign  GT0_RXOUTCLK_OUT                     =  gt0_rxoutclk_i;
    assign  GT1_TXRESETDONE_OUT                  =  gt1_txresetdone_i;
    assign  GT1_RXRESETDONE_OUT                  =  gt1_rxresetdone_i;
    assign  GT1_RXOUTCLK_OUT                     =  gt1_rxoutclk_i;
    assign  GT2_TXRESETDONE_OUT                  =  gt2_txresetdone_i;
    assign  GT2_RXRESETDONE_OUT                  =  gt2_rxresetdone_i;
    assign  GT2_RXOUTCLK_OUT                     =  gt2_rxoutclk_i;
    assign  GT3_TXRESETDONE_OUT                  =  gt3_txresetdone_i;
    assign  GT3_RXRESETDONE_OUT                  =  gt3_rxresetdone_i;
    assign  GT3_RXOUTCLK_OUT                     =  gt3_rxoutclk_i;
    assign  GT0_QPLLLOCK_OUT                     =  gt0_qplllock_i;

generate
if (EXAMPLE_USE_CHIPSCOPE == 1) 
begin : chipscope
    assign  gt0_gttxreset_i                      =  GT0_GTTXRESET_IN;
    assign  gt0_gtrxreset_i                      =  GT0_GTRXRESET_IN;
    assign  gt0_txuserrdy_i                      =  GT0_TXUSERRDY_IN;
    assign  gt0_rxuserrdy_i                      =  GT0_RXUSERRDY_IN;
    assign  gt1_gttxreset_i                      =  GT1_GTTXRESET_IN;
    assign  gt1_gtrxreset_i                      =  GT1_GTRXRESET_IN;
    assign  gt1_txuserrdy_i                      =  GT1_TXUSERRDY_IN;
    assign  gt1_rxuserrdy_i                      =  GT1_RXUSERRDY_IN;
    assign  gt2_gttxreset_i                      =  GT2_GTTXRESET_IN;
    assign  gt2_gtrxreset_i                      =  GT2_GTRXRESET_IN;
    assign  gt2_txuserrdy_i                      =  GT2_TXUSERRDY_IN;
    assign  gt2_rxuserrdy_i                      =  GT2_RXUSERRDY_IN;
    assign  gt3_gttxreset_i                      =  GT3_GTTXRESET_IN;
    assign  gt3_gtrxreset_i                      =  GT3_GTRXRESET_IN;
    assign  gt3_txuserrdy_i                      =  GT3_TXUSERRDY_IN;
    assign  gt3_rxuserrdy_i                      =  GT3_RXUSERRDY_IN;
    assign  gt0_qpllreset_i                      =  GT0_QPLLRESET_IN;
end
endgenerate 

generate
if (EXAMPLE_USE_CHIPSCOPE == 0) 
begin : no_chipscope
    assign  gt0_gttxreset_i                      =  gt0_gttxreset_t;
    assign  gt0_gtrxreset_i                      =  gt0_gtrxreset_t;
    assign  gt0_txuserrdy_i                      =  gt0_txuserrdy_t;
    assign  gt0_rxuserrdy_i                      =  gt0_rxuserrdy_t;
    assign  gt1_gttxreset_i                      =  gt1_gttxreset_t;
    assign  gt1_gtrxreset_i                      =  gt1_gtrxreset_t;
    assign  gt1_txuserrdy_i                      =  gt1_txuserrdy_t;
    assign  gt1_rxuserrdy_i                      =  gt1_rxuserrdy_t;
    assign  gt2_gttxreset_i                      =  gt2_gttxreset_t;
    assign  gt2_gtrxreset_i                      =  gt2_gtrxreset_t;
    assign  gt2_txuserrdy_i                      =  gt2_txuserrdy_t;
    assign  gt2_rxuserrdy_i                      =  gt2_rxuserrdy_t;
    assign  gt3_gttxreset_i                      =  gt3_gttxreset_t;
    assign  gt3_gtrxreset_i                      =  gt3_gtrxreset_t;
    assign  gt3_txuserrdy_i                      =  gt3_txuserrdy_t;
    assign  gt3_rxuserrdy_i                      =  gt3_rxuserrdy_t;
    assign  gt0_qpllreset_i                      =  gt0_qpllreset_t;
end
endgenerate 


ip_gtwizard_v2_4_1x_4ch_TX_STARTUP_FSM #
          (
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),           // Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                        // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                        // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")               // Decision if a manual phase-alignment is necessary or the automatic 
                                                                     // is enough. For single-lane applications the automatic alignment is 
                                                                     // sufficient              
             ) 
gt0_txresetfsm_i      
            ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .TXUSERCLK                      (GT0_TXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .TXRESETDONE                    (gt0_txresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .GTTXRESET                      (gt0_gttxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (gt0_qpllreset_t),
        .CPLL_RESET                     (),
        .TX_FSM_RESET_DONE              (GT0_TX_FSM_RESET_DONE_OUT),
        .TXUSERRDY                      (gt0_txuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RETRY_COUNTER                  ()
           );


ip_gtwizard_v2_4_1x_4ch_TX_STARTUP_FSM #
          (
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),           // Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                        // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                        // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")               // Decision if a manual phase-alignment is necessary or the automatic 
                                                                     // is enough. For single-lane applications the automatic alignment is 
                                                                     // sufficient              
             ) 
gt1_txresetfsm_i      
            ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .TXUSERCLK                      (GT1_TXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .TXRESETDONE                    (gt1_txresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .GTTXRESET                      (gt1_gttxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .TX_FSM_RESET_DONE              (GT1_TX_FSM_RESET_DONE_OUT),
        .TXUSERRDY                      (gt1_txuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RETRY_COUNTER                  ()
           );


ip_gtwizard_v2_4_1x_4ch_TX_STARTUP_FSM #
          (
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),           // Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                        // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                        // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")               // Decision if a manual phase-alignment is necessary or the automatic 
                                                                     // is enough. For single-lane applications the automatic alignment is 
                                                                     // sufficient              
             ) 
gt2_txresetfsm_i      
            ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .TXUSERCLK                      (GT2_TXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .TXRESETDONE                    (gt2_txresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .GTTXRESET                      (gt2_gttxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .TX_FSM_RESET_DONE              (GT2_TX_FSM_RESET_DONE_OUT),
        .TXUSERRDY                      (gt2_txuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RETRY_COUNTER                  ()
           );


ip_gtwizard_v2_4_1x_4ch_TX_STARTUP_FSM #
          (
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),           // Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                        // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                        // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")               // Decision if a manual phase-alignment is necessary or the automatic 
                                                                     // is enough. For single-lane applications the automatic alignment is 
                                                                     // sufficient              
             ) 
gt3_txresetfsm_i      
            ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .TXUSERCLK                      (GT3_TXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .TXRESETDONE                    (gt3_txresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .GTTXRESET                      (gt3_gttxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .TX_FSM_RESET_DONE              (GT3_TX_FSM_RESET_DONE_OUT),
        .TXUSERRDY                      (gt3_txuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RETRY_COUNTER                  ()
           );



ip_gtwizard_v2_4_1x_4ch_RX_STARTUP_FSM  #
          (
           .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .EQ_MODE                  (EQ_MODE),                          //Rx Equalization Mode - Set to DFE or LPM
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),              //Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                           // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                           // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")                 // Decision if a manual phase-alignment is necessary or the automatic 
                                                                         // is enough. For single-lane applications the automatic alignment is 
                                                                         // sufficient              
             )     
gt0_rxresetfsm_i
             ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .RXUSERCLK                      (GT0_RXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .RXRESETDONE                    (gt0_rxresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .RECCLK_STABLE                  (gt0_recclk_stable_i),
        .RECCLK_MONITOR_RESTART         (tied_to_ground_i),
        .DATA_VALID                     (GT0_DATA_VALID_IN),
        .TXUSERRDY                      (tied_to_vcc_i),
        .GTRXRESET                      (gt0_gtrxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .RX_FSM_RESET_DONE              (GT0_RX_FSM_RESET_DONE_OUT),
        .RXUSERRDY                      (gt0_rxuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RXDFELFHOLD                    (gt0_rxdfelfhold_i),
        .RXLPMLFHOLD                    (gt0_rxlpmlfhold_i),
        .RXLPMHFHOLD                    (gt0_rxlpmhfhold_i),
        .RXDFEAGCHOLD                   (),
        .RETRY_COUNTER                  ()
           );
generate
if (EQ_MODE=="DFE") 
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_DFE  #
          (
           .AGC_TIMER       (DFE_ADAPT_LOCK_TIMER)
           )     
gt0_adapt_dfe_i
          ( 
	   .EN(1'b1),
           .CTLE3_COMP_EN(1'b1),
           .GTRXRESET(gt0_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt0_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt0_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT0_DRPCLK_IN),
           .DO(gt0_drpdo_int),
           .DRDY(gt0_drprdy_int),
           .DADDR(gt0_drpaddr_int),
           .DI(gt0_drpdi_int),
           .DEN(gt0_drpen_int),
           .DWE(gt0_drpwe_int),
           .RXMONITOR(gt0_rxmonitorout_o),
           .RXMONITORSEL(gt0_rxmonitorsel_i),
           .AGCHOLD(gt0_rxdfeagchold_i),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt0_adapt_done),
           .DEBUG()
           );
else if (EQ_MODE=="LPM")
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM  #
          (
           .TIMER       (LPM_ADAPT_LOCK_TIMER)
           )     
gt0_adapt_lpm_i
          ( 
	   .EN(1'b1),
           .GTRXRESET(gt0_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt0_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt0_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT0_DRPCLK_IN),
           .DO(gt0_drpdo_int),
           .DRDY(gt0_drprdy_int),
           .DADDR(gt0_drpaddr_int),
           .DI(gt0_drpdi_int),
           .DEN(gt0_drpen_int),
           .DWE(gt0_drpwe_int),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt0_adapt_done),
           .DEBUG()
           );
endgenerate

   assign gt0_drpaddr_i = gt0_adapt_done ? GT0_DRPADDR_IN : gt0_drpaddr_int;
   assign gt0_drpdi_i = gt0_adapt_done ? GT0_DRPDI_IN : gt0_drpdi_int;
   assign gt0_drpen_i = gt0_adapt_done ? GT0_DRPEN_IN : gt0_drpen_int;
   assign gt0_drpwe_i = gt0_adapt_done ? GT0_DRPWE_IN : gt0_drpwe_int;
   assign GT0_DRPDO_OUT = gt0_adapt_done ? gt0_drpdo_o : 16'b0;
   assign GT0_DRPRDY_OUT = gt0_adapt_done ? gt0_drprdy_o : 1'b0;

   assign gt0_drpdo_int = gt0_drpdo_o;
   assign gt0_drprdy_int = gt0_drprdy_o;


ip_gtwizard_v2_4_1x_4ch_RX_STARTUP_FSM  #
          (
           .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .EQ_MODE                  (EQ_MODE),                          //Rx Equalization Mode - Set to DFE or LPM
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),              //Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                           // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                           // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")                 // Decision if a manual phase-alignment is necessary or the automatic 
                                                                         // is enough. For single-lane applications the automatic alignment is 
                                                                         // sufficient              
             )     
gt1_rxresetfsm_i
             ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .RXUSERCLK                      (GT1_RXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .RXRESETDONE                    (gt1_rxresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .RECCLK_STABLE                  (gt1_recclk_stable_i),
        .RECCLK_MONITOR_RESTART         (tied_to_ground_i),
        .DATA_VALID                     (GT1_DATA_VALID_IN),
        .TXUSERRDY                      (tied_to_vcc_i),
        .GTRXRESET                      (gt1_gtrxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .RX_FSM_RESET_DONE              (GT1_RX_FSM_RESET_DONE_OUT),
        .RXUSERRDY                      (gt1_rxuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RXDFELFHOLD                    (gt1_rxdfelfhold_i),
        .RXLPMLFHOLD                    (gt1_rxlpmlfhold_i),
        .RXLPMHFHOLD                    (gt1_rxlpmhfhold_i),
        .RXDFEAGCHOLD                   (),
        .RETRY_COUNTER                  ()
           );
generate
if (EQ_MODE=="DFE") 
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_DFE  #
          (
           .AGC_TIMER       (DFE_ADAPT_LOCK_TIMER)
           )     
gt1_adapt_dfe_i
          ( 
	   .EN(1'b1),
           .CTLE3_COMP_EN(1'b1),
           .GTRXRESET(gt1_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt1_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt1_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT1_DRPCLK_IN),
           .DO(gt1_drpdo_int),
           .DRDY(gt1_drprdy_int),
           .DADDR(gt1_drpaddr_int),
           .DI(gt1_drpdi_int),
           .DEN(gt1_drpen_int),
           .DWE(gt1_drpwe_int),
           .RXMONITOR(gt1_rxmonitorout_o),
           .RXMONITORSEL(gt1_rxmonitorsel_i),
           .AGCHOLD(gt1_rxdfeagchold_i),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt1_adapt_done),
           .DEBUG()
           );
else if (EQ_MODE=="LPM")
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM  #
          (
           .TIMER       (LPM_ADAPT_LOCK_TIMER)
           )     
gt1_adapt_lpm_i
          ( 
	   .EN(1'b1),
           .GTRXRESET(gt1_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt1_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt1_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT1_DRPCLK_IN),
           .DO(gt1_drpdo_int),
           .DRDY(gt1_drprdy_int),
           .DADDR(gt1_drpaddr_int),
           .DI(gt1_drpdi_int),
           .DEN(gt1_drpen_int),
           .DWE(gt1_drpwe_int),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt1_adapt_done),
           .DEBUG()
           );
endgenerate

   assign gt1_drpaddr_i = gt1_adapt_done ? GT1_DRPADDR_IN : gt1_drpaddr_int;
   assign gt1_drpdi_i = gt1_adapt_done ? GT1_DRPDI_IN : gt1_drpdi_int;
   assign gt1_drpen_i = gt1_adapt_done ? GT1_DRPEN_IN : gt1_drpen_int;
   assign gt1_drpwe_i = gt1_adapt_done ? GT1_DRPWE_IN : gt1_drpwe_int;
   assign GT1_DRPDO_OUT = gt1_adapt_done ? gt1_drpdo_o : 16'b0;
   assign GT1_DRPRDY_OUT = gt1_adapt_done ? gt1_drprdy_o : 1'b0;

   assign gt1_drpdo_int = gt1_drpdo_o;
   assign gt1_drprdy_int = gt1_drprdy_o;


ip_gtwizard_v2_4_1x_4ch_RX_STARTUP_FSM  #
          (
           .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .EQ_MODE                  (EQ_MODE),                          //Rx Equalization Mode - Set to DFE or LPM
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),              //Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                           // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                           // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")                 // Decision if a manual phase-alignment is necessary or the automatic 
                                                                         // is enough. For single-lane applications the automatic alignment is 
                                                                         // sufficient              
             )     
gt2_rxresetfsm_i
             ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .RXUSERCLK                      (GT2_RXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .RXRESETDONE                    (gt2_rxresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .RECCLK_STABLE                  (gt2_recclk_stable_i),
        .RECCLK_MONITOR_RESTART         (tied_to_ground_i),
        .DATA_VALID                     (GT2_DATA_VALID_IN),
        .TXUSERRDY                      (tied_to_vcc_i),
        .GTRXRESET                      (gt2_gtrxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .RX_FSM_RESET_DONE              (GT2_RX_FSM_RESET_DONE_OUT),
        .RXUSERRDY                      (gt2_rxuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RXDFELFHOLD                    (gt2_rxdfelfhold_i),
        .RXLPMLFHOLD                    (gt2_rxlpmlfhold_i),
        .RXLPMHFHOLD                    (gt2_rxlpmhfhold_i),
        .RXDFEAGCHOLD                   (),
        .RETRY_COUNTER                  ()
           );
generate
if (EQ_MODE=="DFE") 
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_DFE  #
          (
           .AGC_TIMER       (DFE_ADAPT_LOCK_TIMER)
           )     
gt2_adapt_dfe_i
          ( 
	   .EN(1'b1),
           .CTLE3_COMP_EN(1'b1),
           .GTRXRESET(gt2_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt2_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt2_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT2_DRPCLK_IN),
           .DO(gt2_drpdo_int),
           .DRDY(gt2_drprdy_int),
           .DADDR(gt2_drpaddr_int),
           .DI(gt2_drpdi_int),
           .DEN(gt2_drpen_int),
           .DWE(gt2_drpwe_int),
           .RXMONITOR(gt2_rxmonitorout_o),
           .RXMONITORSEL(gt2_rxmonitorsel_i),
           .AGCHOLD(gt2_rxdfeagchold_i),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt2_adapt_done),
           .DEBUG()
           );
else if (EQ_MODE=="LPM")
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM  #
          (
           .TIMER       (LPM_ADAPT_LOCK_TIMER)
           )     
gt2_adapt_lpm_i
          ( 
	   .EN(1'b1),
           .GTRXRESET(gt2_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt2_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt2_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT2_DRPCLK_IN),
           .DO(gt2_drpdo_int),
           .DRDY(gt2_drprdy_int),
           .DADDR(gt2_drpaddr_int),
           .DI(gt2_drpdi_int),
           .DEN(gt2_drpen_int),
           .DWE(gt2_drpwe_int),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt2_adapt_done),
           .DEBUG()
           );
endgenerate

   assign gt2_drpaddr_i = gt2_adapt_done ? GT2_DRPADDR_IN : gt2_drpaddr_int;
   assign gt2_drpdi_i = gt2_adapt_done ? GT2_DRPDI_IN : gt2_drpdi_int;
   assign gt2_drpen_i = gt2_adapt_done ? GT2_DRPEN_IN : gt2_drpen_int;
   assign gt2_drpwe_i = gt2_adapt_done ? GT2_DRPWE_IN : gt2_drpwe_int;
   assign GT2_DRPDO_OUT = gt2_adapt_done ? gt2_drpdo_o : 16'b0;
   assign GT2_DRPRDY_OUT = gt2_adapt_done ? gt2_drprdy_o : 1'b0;

   assign gt2_drpdo_int = gt2_drpdo_o;
   assign gt2_drprdy_int = gt2_drprdy_o;


ip_gtwizard_v2_4_1x_4ch_RX_STARTUP_FSM  #
          (
           .EXAMPLE_SIMULATION       (EXAMPLE_SIMULATION),
           .GT_TYPE                  ("GTX"), //GTX or GTH or GTP
           .EQ_MODE                  (EQ_MODE),                          //Rx Equalization Mode - Set to DFE or LPM
           .STABLE_CLOCK_PERIOD      (STABLE_CLOCK_PERIOD),              //Period of the stable clock driving this state-machine, unit is [ns]
           .RETRY_COUNTER_BITWIDTH   (8), 
           .TX_QPLL_USED             ("TRUE"),                           // the TX and RX Reset FSMs must 
           .RX_QPLL_USED             ("TRUE"),                           // share these two generic values
           .PHASE_ALIGNMENT_MANUAL   ("FALSE")                 // Decision if a manual phase-alignment is necessary or the automatic 
                                                                         // is enough. For single-lane applications the automatic alignment is 
                                                                         // sufficient              
             )     
gt3_rxresetfsm_i
             ( 
        .STABLE_CLOCK                   (SYSCLK_IN),
        .RXUSERCLK                      (GT3_RXUSRCLK_IN),
        .SOFT_RESET                     (SOFT_RESET_IN),
        .QPLLREFCLKLOST                 (gt0_qpllrefclklost_i),
        .CPLLREFCLKLOST                 (tied_to_ground_i),
        .QPLLLOCK                       (gt0_qplllock_i),
        .CPLLLOCK                       (tied_to_vcc_i),
        .RXRESETDONE                    (gt3_rxresetdone_i),
        .MMCM_LOCK                      (tied_to_vcc_i),
        .RECCLK_STABLE                  (gt3_recclk_stable_i),
        .RECCLK_MONITOR_RESTART         (tied_to_ground_i),
        .DATA_VALID                     (GT3_DATA_VALID_IN),
        .TXUSERRDY                      (tied_to_vcc_i),
        .GTRXRESET                      (gt3_gtrxreset_t),
        .MMCM_RESET                     (),
        .QPLL_RESET                     (),
        .CPLL_RESET                     (),
        .RX_FSM_RESET_DONE              (GT3_RX_FSM_RESET_DONE_OUT),
        .RXUSERRDY                      (gt3_rxuserrdy_t),
        .RUN_PHALIGNMENT                (),
        .RESET_PHALIGNMENT              (),
        .PHALIGNMENT_DONE               (tied_to_vcc_i),
        .RXDFELFHOLD                    (gt3_rxdfelfhold_i),
        .RXLPMLFHOLD                    (gt3_rxlpmlfhold_i),
        .RXLPMHFHOLD                    (gt3_rxlpmhfhold_i),
        .RXDFEAGCHOLD                   (),
        .RETRY_COUNTER                  ()
           );
generate
if (EQ_MODE=="DFE") 
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_DFE  #
          (
           .AGC_TIMER       (DFE_ADAPT_LOCK_TIMER)
           )     
gt3_adapt_dfe_i
          ( 
	   .EN(1'b1),
           .CTLE3_COMP_EN(1'b1),
           .GTRXRESET(gt3_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt3_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt3_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT3_DRPCLK_IN),
           .DO(gt3_drpdo_int),
           .DRDY(gt3_drprdy_int),
           .DADDR(gt3_drpaddr_int),
           .DI(gt3_drpdi_int),
           .DEN(gt3_drpen_int),
           .DWE(gt3_drpwe_int),
           .RXMONITOR(gt3_rxmonitorout_o),
           .RXMONITORSEL(gt3_rxmonitorsel_i),
           .AGCHOLD(gt3_rxdfeagchold_i),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt3_adapt_done),
           .DEBUG()
           );
else if (EQ_MODE=="LPM")
ip_gtwizard_v2_4_1x_4ch_ADAPT_TOP_LPM  #
          (
           .TIMER       (LPM_ADAPT_LOCK_TIMER)
           )     
gt3_adapt_lpm_i
          ( 
	   .EN(1'b1),
           .GTRXRESET(gt3_gtrxreset_i), //reset going to the GT, coming from either chipscope or TB
           .RXPMARESET(gt3_rxpmareset_i),//tied to ground, going to GT
           .RXDFELPMRESET(gt3_rxdfelpmreset_i),//tied to groun, going to GT
           .DCLK(GT3_DRPCLK_IN),
           .DO(gt3_drpdo_int),
           .DRDY(gt3_drprdy_int),
           .DADDR(gt3_drpaddr_int),
           .DI(gt3_drpdi_int),
           .DEN(gt3_drpen_int),
           .DWE(gt3_drpwe_int),
           .KLHOLD(),
           .KHHOLD(),
           .DONE(gt3_adapt_done),
           .DEBUG()
           );
endgenerate

   assign gt3_drpaddr_i = gt3_adapt_done ? GT3_DRPADDR_IN : gt3_drpaddr_int;
   assign gt3_drpdi_i = gt3_adapt_done ? GT3_DRPDI_IN : gt3_drpdi_int;
   assign gt3_drpen_i = gt3_adapt_done ? GT3_DRPEN_IN : gt3_drpen_int;
   assign gt3_drpwe_i = gt3_adapt_done ? GT3_DRPWE_IN : gt3_drpwe_int;
   assign GT3_DRPDO_OUT = gt3_adapt_done ? gt3_drpdo_o : 16'b0;
   assign GT3_DRPRDY_OUT = gt3_adapt_done ? gt3_drprdy_o : 1'b0;

   assign gt3_drpdo_int = gt3_drpdo_o;
   assign gt3_drprdy_int = gt3_drprdy_o;


  always @(posedge SYSCLK_IN)
  begin
        if(gt0_gtrxreset_i)
        begin
          rx_cdrlocked       <= `DLY    1'b0;
          rx_cdrlock_counter <= `DLY    0;      
        end                
        else if (rx_cdrlock_counter == WAIT_TIME_CDRLOCK) 
        begin
          rx_cdrlocked       <= `DLY    1'b1;
          rx_cdrlock_counter <= `DLY    rx_cdrlock_counter;
        end
        else
          rx_cdrlock_counter <= `DLY    rx_cdrlock_counter + 1;
  end 

assign  gt0_recclk_stable_i                  =  rx_cdrlocked;
assign  gt1_recclk_stable_i                  =  rx_cdrlocked;
assign  gt2_recclk_stable_i                  =  rx_cdrlocked;
assign  gt3_recclk_stable_i                  =  rx_cdrlocked;








endmodule


