////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 2.4
//  \   \         Application : 7 Series FPGAs Transceivers Wizard 
//  /   /         Filename : ip_gtwizard_v2_4_1x_4ch_lpm_loop_fsm.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module ip_gtwizard_v2_4_1x_4ch_lpm_loop_fsm
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1
/////////AGC LOOP SETTLING CODE///////

module ip_gtwizard_v2_4_1x_4ch_lpm_loop_fsm #(
	parameter usr_clk=3)
	(

	
	input  DCLK,reset,DRDY,
	input[15:0] D0,
	output  [1:0] holds,
	output  [15:0] DI,
	output  [8:0] DADDR,
	output  DWE,DEN,
	output kill3,

	// Debug Ports//
	output [4:0] state,
	output [31:0] count_lock_out,
	output [15:0] store_di0,
	output start,enable,kill0,kill1,kill2,lock0,lock1,lock2,lock3

	);
        
        wire rd_drp;
	wire wr_drp;

	assign DWE=wr_drp;
	assign DEN= rd_drp | wr_drp;

	drp_wr_fsm_lpm I1(	
	.lock0(lock0),
	.lock1(lock1),
	.lock2(lock2),
	.lock3(lock3),
	.clk(DCLK),
	.reset(reset),
	.ready(DRDY),
	.holds(holds),
	.kill0(kill0),
	.store_di0(store_di0),
	.kill1(kill1),
	.kill2(kill2),
	.kill3(kill3),
	.state(state),
	.DI(DI),
	.di0(D0),
	.Address(DADDR),
	.rd_drp(rd_drp),
	.wr_drp(wr_drp)
	);


	lock_detect_lpm # (.usr_clk(usr_clk)) I2( 
	.start(start),
	.count_lock_out(count_lock_out),
	.dclk(DCLK),
	.reset(reset),
	.lock0(lock0),
	.lock1(lock1),
	.lock2(lock2),
	.lock3(lock3)
	);

	counter_lpm I3(
	.dclk(DCLK),
	.reset(reset) ,
        .count_lock_out(count_lock_out),
	.start(start),
	.stop(done) );

endmodule



module drp_wr_fsm_lpm(

         input lock0,lock1,lock2,lock3,clk,reset,ready,
	 input[15:0] di0,
    	 output reg [1:0] holds =0,
    	 output reg [15:0] DI =0,
	 output reg[15:0] store_di0 ,
    	 output reg [8:0] Address =0,
	 output reg[4:0] state ,
	 output reg kill0 ,kill1 ,kill2 ,kill3 ,
	 output reg rd_drp =0,
	 output reg wr_drp =0
    );


  	


reg done0,done1,done2,done3;
initial store_di0 =0;
parameter       
                load_addr_kl=      1,
                rd_drp_kl=         2,
                wait_drprdy_kl=    3,
		mod_drp_kl=        4,
                load_drp_kl =      5,
                 pulse_wr_kl=      6,
                wait_drp_dy_kl=    7, 

		load_addr_kh=      8,
                rd_drp_kh=         9,
                wait_drprdy_kh=    10,
		mod_drp_kh=        11,
                load_drp_kh =      12,
                pulse_wr_kh=       13,
                wait_drp_dy_kh=    14,  
             

		endstate        =   15,
	        resetstate      =   16;					
					  
initial	   holds =2'b0;
initial    DI =16'b0;
initial    Address =9'b0;
initial    wr_drp =1'b0;					 
initial    rd_drp =1'b0;
initial    state =0;
initial    done0=0;
initial    done1=0;
initial    done2=0;
initial    done3=0;

initial    kill0 =0;
initial    kill1 =0;
initial    kill2 =0;
initial    kill3 =0;

					 
always @(posedge clk)

     if(reset)
	  begin
	  state <=resetstate;
	  holds <=2'b0;
          DI <=16'b0; 
          Address <=9'b0;
          wr_drp <=1'b0;
	  rd_drp <=1'b0;
	  store_di0<=0;
	  done0<=0;
	  done1<=0;	
	  done2<=0;
	  done3<=0;
          kill0 <=0;
	  kill1 <=0;	
	  kill2 <=0;
	  kill3 <=0;
	  end
	  else  
	  
	  begin
	  if( (lock0 &&  !lock1 && !lock2 && !lock3 ) && !kill0 )
	  
	  begin
         	  
	  case (state )
	  
	 	  
	  resetstate: begin
	              state <=   load_addr_kl;
		      done0<=0;
		      holds <=2'b00;
		      end


 //// KL LOOP  ////
		
		
		
      load_addr_kl:     begin 
                        Address <=9'h02B; 
                        state <=rd_drp_kl;
                        end

      rd_drp_kl:        begin                    // Start Read Sequence Wait for DRPRDY
			rd_drp <=1'b1;
			state <=wait_drprdy_kl;
			end

      wait_drprdy_kl:   begin                    //  Wait for DRPRDY
			if(ready)
                        begin
 			store_di0<=di0;				
			state <=mod_drp_kl;
			end
			end

      
      mod_drp_kl:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0100;
			state <=load_drp_kl;
			end

		
      load_drp_kl:      begin 					
			state <= pulse_wr_kl;
			DI <=store_di0;
			end
								
	               
					 	
      pulse_wr_kl:      begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kl;
			end
						
     wait_drp_dy_kl:    begin
			wr_drp <=1'b0; 					
			if( ready )
                       	begin 
			state <=load_addr_kh;  
                       	end
			end	

	 

          ////// KH LOOP  //////

      load_addr_kh:     begin 
                        Address <=9'h02A; 
                        state <=rd_drp_kh;
                        store_di0<=0;
 			DI <=0;
                        end

              		rd_drp_kh: begin                    // Start Read Sequence Wait for DRPRDY
		        rd_drp <=1'b1;
			state <=wait_drprdy_kh;
			end

			wait_drprdy_kh: begin               //  Wait for DRPRDY
			if(ready) begin
			rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kh;
			end 
         		end

			mod_drp_kh: begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0100;
			state <=load_drp_kh;
			end

		
      load_drp_kh:      begin 					
			state <=pulse_wr_kh;
			DI <=store_di0;
			end 
	               
					 	
     pulse_wr_kh:       begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kh;
			end
						
     wait_drp_dy_kh:    begin  if( ready )
                        begin 					
		        wr_drp <=1'b0;
                        done0<=1;
		        state <=endstate;  
                        end
		        end	
							
     endstate:         begin
		       DI <=16'd0;
		       Address <=9'd0;
		       wr_drp <=1'b0;
		       rd_drp <=1'b0;
		       kill0 <=done0;
		       store_di0<=0;
		       state <=resetstate;
		       end
		
     default:  state  <=  5'bx; 
 
     endcase	
     end

     else 
    
     if((lock1 && !lock2 && !lock3 ) && !kill1 )
	  begin
         	  
	  case (state )
	  	  
	  resetstate: begin
	              state <= load_addr_kl;
		      store_di0<=0;DI <=0;
		      done1<=0;
		      end


 //// KL LOOP  ////
		
		
		
      load_addr_kl:     begin 
                        Address <=9'h02B; 
			store_di0<=0;
                        state <=rd_drp_kl;
                        end

      rd_drp_kl:        begin                    // Start Read Sequence Wait for DRPRDY
			rd_drp <=1'b1;
			state <=wait_drprdy_kl;
			end

      wait_drprdy_kl:   begin                    //  Wait for DRPRDY
			if(ready) begin
                       	rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kl;
			end  end

      mod_drp_kl:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0011;
			state <=load_drp_kl;
			end

		
      load_drp_kl:      begin 					
			state <= pulse_wr_kl;
			DI <=store_di0;
			end  
	               
					 	
      pulse_wr_kl:      begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kl;
			end
						
     wait_drp_dy_kl:   begin  if( ready )
                        begin 
			wr_drp <=1'b0;
                        state <=load_addr_kh;  
                        end	 end

	 

          ////// KH LOOP  //////

      load_addr_kh:     begin 
                        Address <=9'h02A; 
			store_di0<=0;DI <=0;
                        state <=rd_drp_kh; 
                        end

      rd_drp_kh:        begin                    // Start Read Sequence Wait for DRPRDY
		        rd_drp <=1'b1;
			state <=wait_drprdy_kh;
			end

      wait_drprdy_kh:   begin                    //  Wait for DRPRDY
			if(ready) begin
			rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kh;
			end  end

      mod_drp_kh:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0011;
			state <=load_drp_kh;
			end

		
      load_drp_kh:      begin 					
			state <=pulse_wr_kh;
			DI <=store_di0;
			end 
	               
					 	
     pulse_wr_kh:       begin					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kh;
			end
						
     wait_drp_dy_kh:    begin   if( ready )
                        begin 
			wr_drp <=1'b0;
                        done1<=1;
			state <=endstate;  
                        end	 end

 
								
     endstate:         begin
			DI <=16'd0;
			Address <=9'd0;
			wr_drp <=1'b0;
			rd_drp <=1'b0;
			kill1 <=done1;
			store_di0<=0;
			state <=resetstate; 
			end

		
     default:  state  <=  5'bx; 
 
     endcase
     end	  
     else 
	  
	  if( lock2 && !lock3 && !kill2 )
	  begin
         	  
	  case (state )
	
	  
	  resetstate: begin
	              state <= load_addr_kl;
		      done2<=0;
		      end


 //// KL LOOP  ////
		
		
		
      load_addr_kl:     begin 
                        Address <=9'h02B; 
 			store_di0<=0;DI <=0;
                        state <=rd_drp_kl;
                        end

      rd_drp_kl:        begin                    // Start Read Sequence Wait for DRPRDY
			rd_drp <=1'b1;
			state <=wait_drprdy_kl;
			end

      wait_drprdy_kl:   begin                    //  Wait for DRPRDY
			if(ready)  begin
                        rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kl;
			end  end

      mod_drp_kl:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0010;
			state <=load_drp_kl;
			end

		
      load_drp_kl:      begin 					
			state <= pulse_wr_kl;
			DI <=store_di0;
			end  
	               
					 	
      pulse_wr_kl:      begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kl;
			end
						
     wait_drp_dy_kl:  begin  if( ready )
                        begin 
			wr_drp <=1'b0;
                        state <=load_addr_kh;  
                        end	end

	 

          ////// KH LOOP  //////

      load_addr_kh:     begin 
                        Address <=9'h02A; 
			store_di0<=0;DI <=0;
                        state <=rd_drp_kh; 
                        end

      rd_drp_kh:        begin                    // Start Read Sequence Wait for DRPRDY
		        rd_drp <=1'b1;
			state <=wait_drprdy_kh;
			end
      wait_drprdy_kh:   begin                    //  Wait for DRPRDY
			if(ready) begin
			rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kh;
			end  end

      mod_drp_kh:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0010;
			state <=load_drp_kh;
			end

		
      load_drp_kh:      begin 					
			state <=pulse_wr_kh;
			DI <=store_di0;
			end  
	               
					 	
     pulse_wr_kh:       begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kh;
			end
						
     wait_drp_dy_kh:   begin  if( ready )
                        begin 
			wr_drp <=1'b0;
                        done2<=1;
			state <=endstate;  
                        end  end	


								
     endstate:          begin
			DI <=16'd0;
			Address <=9'd0;
			wr_drp <=1'b0;
			rd_drp <=1'b0;
			store_di0<=0;
			kill2 <=done2;
			state <=resetstate; 
			end

		
     default:  state  <=  5'bx; 
 
     endcase
     end

     else 
	  
	  if( (lock3) && !kill3 )
	  begin
         	  
	  case (state )
	  
	  
	  
	  resetstate: begin
	              state <= load_addr_kl;
		      done3<=0;
		      end


 //// KL LOOP  ////
		
		
		
      load_addr_kl:     begin 
                        Address <=9'h02B; 
			store_di0<=0;DI <=0;
                        state <=rd_drp_kl;
                        end

      rd_drp_kl:        begin                    // Start Read Sequence Wait for DRPRDY
			rd_drp <=1'b1;
			state <=wait_drprdy_kl;
			end

      wait_drprdy_kl:   begin                    //  Wait for DRPRDY
			if(ready)  begin
                        rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kl;
			end  end

      mod_drp_kl:       begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0000;
			state <=load_drp_kl;
			end

		
      load_drp_kl:      begin 					
			state <= pulse_wr_kl;
			DI <=store_di0;
			end 
	               
					 	
      pulse_wr_kl:      begin 					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kl;
			end
						
     wait_drp_dy_kl:    begin  if( ready )
                        begin 
			wr_drp <=1'b0;
                        state <=load_addr_kh;  
                        end
			end

	 

          ////// KH LOOP  //////

      load_addr_kh:     begin 
                        Address <=9'h02A; 
			store_di0<=0;DI <=0;
                        state <=rd_drp_kh; 
                        end

      rd_drp_kh:        begin                    // Start Read Sequence Wait for DRPRDY
		        rd_drp <=1'b1;
			state <=wait_drprdy_kh;
			end

     wait_drprdy_kh:    begin                    //  Wait for DRPRDY
			if(ready) begin
			rd_drp <=1'b0;				
			store_di0<=di0;
			state <=mod_drp_kh;
			end  end

     mod_drp_kh:        begin 
			rd_drp <=1'b0;
			store_di0[11:8]<=4'b0000;
			state <=load_drp_kh;
			end

		
      load_drp_kh:      begin 					
			state <=pulse_wr_kh;
			DI <=store_di0;
			end  
	               
					 	
     pulse_wr_kh:       begin					
			wr_drp <=1'b1;
			state <=wait_drp_dy_kh;
			end
						
     wait_drp_dy_kh:    begin
    			if( ready )
                        begin 
			wr_drp <=1'b0;
                       	done3<=1;
			state <=endstate;  
                        end  end	


								
     endstate:          begin
			holds <=2'b11;
			DI <=16'd0;
			Address <=9'd0;
			wr_drp <=1'b0;
			rd_drp <=1'b0;
			store_di0<=0;
			kill3 <=done3;
			state <=resetstate; 
			end

		
     default:  state  <=  5'bx; 
 
     endcase
     end
     end

endmodule


module lock_detect_lpm #(parameter usr_clk = 150) ( dclk,reset,lock0,lock1,lock2,lock3,start,count_lock_out);
  
  output lock0,lock1,lock2,lock3,start;
  input[31:0] count_lock_out;
  input dclk,reset;
  reg lock0,lock1,lock2,lock3,start;
  initial start=0;
 
  initial lock0=0;
  initial lock1=0;
  initial lock2=0;
  initial lock3=0;
  
   always @ (posedge dclk)
   begin
   if (reset == 1'b1) begin
   lock0<=0;
   lock1<=0;
   lock2<=0;
   lock3<=0;
   start<=0;  
   
   end

   else   begin
 
   start<=1;

   if  (count_lock_out==5)
   begin
   lock0<=1; end


   else if  (count_lock_out==(1500*usr_clk))
   begin
   lock1<=1; end


   else  if  (count_lock_out==(3000*usr_clk)) begin
   lock2<=1; end
   else  if  (count_lock_out==(4500*usr_clk)) begin
   lock3<=1;
   start<=0;

   end
   end
   end

endmodule




module counter_lpm (dclk, reset , count_lock_out,start,stop);
input reset,start,stop;
input dclk ;

output [31:0] count_lock_out ;

reg [31:0] count_lock_out ;
initial count_lock_out=0;


always @ (posedge dclk)
begin : COUNTER

if (reset == 1'b1 |  stop == 1'b1) begin
count_lock_out <= 32'b0;
end

else if (start == 1'b1  ) begin
count_lock_out <= count_lock_out + 1; end
else  begin

count_lock_out<=0; end

end
endmodule

