`timescale 1ns / 1ps

module srio_base_shell (
    input  wire Q2_CLK1_GTREFCLK_PAD_N_IN,
    input  wire Q2_CLK1_GTREFCLK_PAD_P_IN,
    input  wire CLK_IN_50M,
    input  wire RXN_IN,
    input  wire RXP_IN,
    output wire TXN_OUT,
    output wire TXP_OUT,
    input  wire ad9516_ld_in,
    output wire ad9516_cs_n_out,
    output wire ad9516_sclk_out,
    output wire ad9516_sdata_out,
    output wire ad9516_refsel_out,
    output wire ad9516_pdwn_out,
    output wire ad9516_rstn_out,
    output wire ad9516_syn_n_out,
    output wire TRACK_DATA_OUT,
    output wire         DBG_GT0_CPLLLOCK,
    output wire         DBG_GT0_CPLLFBCLKLOST,
    output wire         DBG_GT0_TXRESETDONE,
    output wire         DBG_GT0_TXFSMRESETDONE,
    output wire         DBG_GT0_TX_SYSTEM_RESET,
    output wire         DBG_GT0_TXUSERRDY,
    output wire         DBG_GT0_GTTXRESET,
    output wire         DBG_GT0_TXPMARESET,
    output wire         DBG_GT0_TXPCSRESET,
    output wire [31:0]  DBG_GT0_TXDATA,
    output wire [3:0]   DBG_GT0_TXCHARISK,
    output wire [8:0]   DBG_GT0_TX_READ_COUNTER,
    output wire         DBG_GT0_TXUSRCLK2,
    output wire         DBG_GT0_RXRESETDONE,
    output wire         DBG_GT0_RXFSMRESETDONE,
    output wire         DBG_GT0_RX_SYSTEM_RESET,
    output wire         DBG_GT0_RXUSERRDY,
    output wire         DBG_GT0_GTRXRESET,
    output wire         DBG_GT0_RXPMARESET,
    output wire         DBG_GT0_RXPCSRESET,
    output wire [31:0]  DBG_GT0_RXDATA,
    output wire [3:0]   DBG_GT0_RXCHARISK,
    output wire [7:0]   DBG_GT0_ERROR_COUNT,
    output wire         DBG_GT0_TRACK_DATA,
    output wire [3:0]   DBG_GT0_RXDISPERR,
    output wire [3:0]   DBG_GT0_RXNOTINTABLE,
    output wire         DBG_GT0_RXBYTEISALIGNED,
    output wire         DBG_GT0_RXBYTEREALIGN,
    output wire         DBG_GT0_RXCOMMADET,
    output wire         DBG_GT0_RXMCOMMAALIGNEN,
    output wire         DBG_GT0_RXPCOMMAALIGNEN,
    output wire [1:0]   DBG_GT0_RXCLKCORCNT,
    output wire [31:0]  DBG_GT0_RXDATA_ALIGNED,
    output wire [31:0]  DBG_GT0_RXDATA_TRACK,
    output wire [1:0]   DBG_GT0_RXALIGN_SEL,
    output wire         DBG_GT0_RXSTART_OF_PACKET,
    output wire         DBG_GT0_RXUSRCLK2,
    output wire [31:0]  DBG_HV_PACKET_OUT,
    output wire [15:0]  DBG_HV_CURRENT_ADDR,
    output wire         DBG_HV_PACKET_VALID,
    output wire         DBG_HV_USING_INTERNAL_SOURCE,
    output wire [31:0]  DBG_HV_RX_PACKET_OUT,
    output wire [15:0]  DBG_HV_RX_CURRENT_ADDR,
    output wire [15:0]  DBG_HV_RX_CURRENT_DATA,
    output wire [15:0]  DBG_HV_RX_EXPECTED_ADDR,
    output wire         DBG_HV_RX_PACKET_SEEN,
    output wire         DBG_HV_RX_ADDR_IN_RANGE,
    output wire         DBG_HV_RX_SEQ_LOCKED,
    output wire         DBG_HV_RX_SEQ_OK,
    output wire [7:0]   DBG_HV_RX_SEQ_ERROR_COUNT,
    output wire         DBG_SOFT_RESET,
    output wire         DBG_DRPCLK_HEARTBEAT
);

gtwizard_0_exdes u_gtwizard_0_exdes (
    .Q2_CLK1_GTREFCLK_PAD_N_IN(Q2_CLK1_GTREFCLK_PAD_N_IN),
    .Q2_CLK1_GTREFCLK_PAD_P_IN(Q2_CLK1_GTREFCLK_PAD_P_IN),
    .CLK_IN_50M(CLK_IN_50M),
    .TRACK_DATA_OUT(TRACK_DATA_OUT),
    .RXN_IN(RXN_IN),
    .RXP_IN(RXP_IN),
    .TXN_OUT(TXN_OUT),
    .TXP_OUT(TXP_OUT),
    .ad9516_ld_in(ad9516_ld_in),
    .ad9516_cs_n_out(ad9516_cs_n_out),
    .ad9516_sclk_out(ad9516_sclk_out),
    .ad9516_sdata_out(ad9516_sdata_out),
    .ad9516_refsel_out(ad9516_refsel_out),
    .ad9516_pdwn_out(ad9516_pdwn_out),
    .ad9516_rstn_out(ad9516_rstn_out),
    .ad9516_syn_n_out(ad9516_syn_n_out),
    .DBG_GT0_CPLLLOCK(DBG_GT0_CPLLLOCK),
    .DBG_GT0_CPLLFBCLKLOST(DBG_GT0_CPLLFBCLKLOST),
    .DBG_GT0_TXRESETDONE(DBG_GT0_TXRESETDONE),
    .DBG_GT0_TXFSMRESETDONE(DBG_GT0_TXFSMRESETDONE),
    .DBG_GT0_TX_SYSTEM_RESET(DBG_GT0_TX_SYSTEM_RESET),
    .DBG_GT0_TXUSERRDY(DBG_GT0_TXUSERRDY),
    .DBG_GT0_GTTXRESET(DBG_GT0_GTTXRESET),
    .DBG_GT0_TXPMARESET(DBG_GT0_TXPMARESET),
    .DBG_GT0_TXPCSRESET(DBG_GT0_TXPCSRESET),
    .DBG_GT0_TXDATA(DBG_GT0_TXDATA),
    .DBG_GT0_TXCHARISK(DBG_GT0_TXCHARISK),
    .DBG_GT0_TX_READ_COUNTER(DBG_GT0_TX_READ_COUNTER),
    .DBG_GT0_TXUSRCLK2(DBG_GT0_TXUSRCLK2),
    .DBG_GT0_RXRESETDONE(DBG_GT0_RXRESETDONE),
    .DBG_GT0_RXFSMRESETDONE(DBG_GT0_RXFSMRESETDONE),
    .DBG_GT0_RX_SYSTEM_RESET(DBG_GT0_RX_SYSTEM_RESET),
    .DBG_GT0_RXUSERRDY(DBG_GT0_RXUSERRDY),
    .DBG_GT0_GTRXRESET(DBG_GT0_GTRXRESET),
    .DBG_GT0_RXPMARESET(DBG_GT0_RXPMARESET),
    .DBG_GT0_RXPCSRESET(DBG_GT0_RXPCSRESET),
    .DBG_GT0_RXDATA(DBG_GT0_RXDATA),
    .DBG_GT0_RXCHARISK(DBG_GT0_RXCHARISK),
    .DBG_GT0_ERROR_COUNT(DBG_GT0_ERROR_COUNT),
    .DBG_GT0_TRACK_DATA(DBG_GT0_TRACK_DATA),
    .DBG_GT0_RXDISPERR(DBG_GT0_RXDISPERR),
    .DBG_GT0_RXNOTINTABLE(DBG_GT0_RXNOTINTABLE),
    .DBG_GT0_RXBYTEISALIGNED(DBG_GT0_RXBYTEISALIGNED),
    .DBG_GT0_RXBYTEREALIGN(DBG_GT0_RXBYTEREALIGN),
    .DBG_GT0_RXCOMMADET(DBG_GT0_RXCOMMADET),
    .DBG_GT0_RXMCOMMAALIGNEN(DBG_GT0_RXMCOMMAALIGNEN),
    .DBG_GT0_RXPCOMMAALIGNEN(DBG_GT0_RXPCOMMAALIGNEN),
    .DBG_GT0_RXCLKCORCNT(DBG_GT0_RXCLKCORCNT),
    .DBG_GT0_RXDATA_ALIGNED(DBG_GT0_RXDATA_ALIGNED),
    .DBG_GT0_RXDATA_TRACK(DBG_GT0_RXDATA_TRACK),
    .DBG_GT0_RXALIGN_SEL(DBG_GT0_RXALIGN_SEL),
    .DBG_GT0_RXSTART_OF_PACKET(DBG_GT0_RXSTART_OF_PACKET),
    .DBG_GT0_RXUSRCLK2(DBG_GT0_RXUSRCLK2),
    .DBG_HV_PACKET_OUT(DBG_HV_PACKET_OUT),
    .DBG_HV_CURRENT_ADDR(DBG_HV_CURRENT_ADDR),
    .DBG_HV_PACKET_VALID(DBG_HV_PACKET_VALID),
    .DBG_HV_USING_INTERNAL_SOURCE(DBG_HV_USING_INTERNAL_SOURCE),
    .DBG_HV_RX_PACKET_OUT(DBG_HV_RX_PACKET_OUT),
    .DBG_HV_RX_CURRENT_ADDR(DBG_HV_RX_CURRENT_ADDR),
    .DBG_HV_RX_CURRENT_DATA(DBG_HV_RX_CURRENT_DATA),
    .DBG_HV_RX_EXPECTED_ADDR(DBG_HV_RX_EXPECTED_ADDR),
    .DBG_HV_RX_PACKET_SEEN(DBG_HV_RX_PACKET_SEEN),
    .DBG_HV_RX_ADDR_IN_RANGE(DBG_HV_RX_ADDR_IN_RANGE),
    .DBG_HV_RX_SEQ_LOCKED(DBG_HV_RX_SEQ_LOCKED),
    .DBG_HV_RX_SEQ_OK(DBG_HV_RX_SEQ_OK),
    .DBG_HV_RX_SEQ_ERROR_COUNT(DBG_HV_RX_SEQ_ERROR_COUNT),
    .DBG_SOFT_RESET(DBG_SOFT_RESET),
    .DBG_DRPCLK_HEARTBEAT(DBG_DRPCLK_HEARTBEAT)
);

endmodule
