module custom_gtx_phy_wrapper_template (
    input  wire        sys_clk,
    input  wire        rst,

    input  wire [31:0] tx_data,
    input  wire        tx_valid,
    input  wire        tx_last,
    input  wire [1:0]  tx_word_index,

    input  wire        gt_refclk_p,
    input  wire        gt_refclk_n,
    input  wire        sfp_rx_p,
    input  wire        sfp_rx_n,
    output wire        sfp_tx_p,
    output wire        sfp_tx_n,

    output wire        phy_tx_resetdone,
    output wire        phy_rx_resetdone,
    output wire        phy_channel_up,
    output wire [31:0] phy_debug_status
);

    wire        txusrclk;
    wire        txusrclk2;
    wire        qpll_lock;
    wire        tx_resetdone_i;
    wire        rx_resetdone_i;

    assign txusrclk = sys_clk;
    assign txusrclk2 = sys_clk;

    /*
     * Replace `gtx_sfp_phy_0` with the actual wrapper generated by
     * Vivado 2017.4 Transceivers Wizard.
     *
     * Common ports you are likely to see in the wrapper:
     * - soft_reset_tx_in / soft_reset_rx_in
     * - gt0_gtxrxp_in / gt0_gtxrxn_in
     * - gt0_gtxtxp_out / gt0_gtxtxn_out
     * - gt0_txusrclk_in / gt0_txusrclk2_in
     * - gt0_rxusrclk_in / gt0_rxusrclk2_in
     * - gt0_drpclk_in
     * - gt0_gtrefclk0_in or gt0_gtrefclk1_in
     * - gt0_txdata_in[31:0]
     * - gt0_txcharisk_in[3:0] or gt0_txctrl* depending on coding mode
     * - gt0_txresetdone_out
     * - gt0_rxresetdone_out
     * - gt0_qplllock_out / common lock output
     */

    /*
    gtx_sfp_phy_0 u_gtx_sfp_phy_0 (
        .soft_reset_tx_in (rst),
        .soft_reset_rx_in (rst),
        .gt0_drpclk_in    (sys_clk),
        .gt0_gtxrxp_in    (sfp_rx_p),
        .gt0_gtxrxn_in    (sfp_rx_n),
        .gt0_gtxtxp_out   (sfp_tx_p),
        .gt0_gtxtxn_out   (sfp_tx_n),
        .gt0_gtrefclk1_in (gt_refclk_p),
        .gt0_txusrclk_in  (txusrclk),
        .gt0_txusrclk2_in (txusrclk2),
        .gt0_txdata_in    (tx_data),
        .gt0_txcharisk_in (4'b0000),
        .gt0_txresetdone_out(tx_resetdone_i),
        .gt0_rxresetdone_out(rx_resetdone_i),
        .gt0_qplllock_out (qpll_lock)
    );
    */

    assign sfp_tx_p         = 1'b0;
    assign sfp_tx_n         = 1'b1;
    assign phy_tx_resetdone = tx_resetdone_i;
    assign phy_rx_resetdone = rx_resetdone_i;
    assign phy_channel_up   = qpll_lock & tx_resetdone_i;
    assign phy_debug_status = {
        20'd0,
        tx_word_index,
        tx_last,
        tx_valid,
        qpll_lock,
        rx_resetdone_i,
        tx_resetdone_i
    };

endmodule
