///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 2.4
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : ip_gtwizard_v2_4_1x_4ch.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module ip_gtwizard_v2_4_1x_4ch (a GT Wrapper)
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`default_nettype wire

`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************

(* CORE_GENERATION_INFO = "ip_gtwizard_v2_4_1x_4ch,gtwizard_v2_4,{protocol_file=aurora_64b66b}" *) module ip_gtwizard_v2_4_1x_4ch #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTRESET_SPEEDUP    =   "false",     // Set to "true" to speed up sim reset
    parameter   RX_DFE_KL_CFG2_IN              =   32'h3010D90C,
    parameter   PMA_RSV_IN                     =   32'h001E7080,
    parameter   SIM_VERSION                    =   "4.0"
)
(
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y8)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT0_DRPADDR_IN,
    input           GT0_DRPCLK_IN,
    input   [15:0]  GT0_DRPDI_IN,
    output  [15:0]  GT0_DRPDO_OUT,
    input           GT0_DRPEN_IN,
    output          GT0_DRPRDY_OUT,
    input           GT0_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT0_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT0_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT0_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT0_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT0_RXUSRCLK_IN,
    input           GT0_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT0_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT0_RXPRBSERR_OUT,
    input   [2:0]   GT0_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT0_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT0_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT0_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT0_RXBUFRESET_IN,
    output  [2:0]   GT0_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT0_RXDFEAGCHOLD_IN,
    input           GT0_RXDFELPMRESET_IN,
    output  [6:0]   GT0_RXMONITOROUT_OUT,
    input   [1:0]   GT0_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT0_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT0_RXDATAVALID_OUT,
    output  [1:0]   GT0_RXHEADER_OUT,
    output          GT0_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT0_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT0_GTRXRESET_IN,
    input           GT0_RXPCSRESET_IN,
    input           GT0_RXPMARESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT0_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT0_GTTXRESET_IN,
    input           GT0_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT0_TXUSRCLK_IN,
    input           GT0_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT0_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT0_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT0_GTXTXN_OUT,
    output          GT0_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT0_TXOUTCLK_OUT,
    output          GT0_TXOUTCLKFABRIC_OUT,
    output          GT0_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT0_TXHEADER_IN,
    input   [6:0]   GT0_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT0_TXPCSRESET_IN,
    output          GT0_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT0_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y9)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT1_DRPADDR_IN,
    input           GT1_DRPCLK_IN,
    input   [15:0]  GT1_DRPDI_IN,
    output  [15:0]  GT1_DRPDO_OUT,
    input           GT1_DRPEN_IN,
    output          GT1_DRPRDY_OUT,
    input           GT1_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT1_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT1_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT1_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT1_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT1_RXUSRCLK_IN,
    input           GT1_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT1_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT1_RXPRBSERR_OUT,
    input   [2:0]   GT1_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT1_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT1_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT1_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT1_RXBUFRESET_IN,
    output  [2:0]   GT1_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT1_RXDFEAGCHOLD_IN,
    input           GT1_RXDFELPMRESET_IN,
    output  [6:0]   GT1_RXMONITOROUT_OUT,
    input   [1:0]   GT1_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT1_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT1_RXDATAVALID_OUT,
    output  [1:0]   GT1_RXHEADER_OUT,
    output          GT1_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT1_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT1_GTRXRESET_IN,
    input           GT1_RXPCSRESET_IN,
    input           GT1_RXPMARESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT1_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT1_GTTXRESET_IN,
    input           GT1_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT1_TXUSRCLK_IN,
    input           GT1_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT1_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT1_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT1_GTXTXN_OUT,
    output          GT1_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT1_TXOUTCLK_OUT,
    output          GT1_TXOUTCLKFABRIC_OUT,
    output          GT1_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT1_TXHEADER_IN,
    input   [6:0]   GT1_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT1_TXPCSRESET_IN,
    output          GT1_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT1_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y10)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT2_DRPADDR_IN,
    input           GT2_DRPCLK_IN,
    input   [15:0]  GT2_DRPDI_IN,
    output  [15:0]  GT2_DRPDO_OUT,
    input           GT2_DRPEN_IN,
    output          GT2_DRPRDY_OUT,
    input           GT2_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT2_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT2_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT2_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT2_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT2_RXUSRCLK_IN,
    input           GT2_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT2_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT2_RXPRBSERR_OUT,
    input   [2:0]   GT2_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT2_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT2_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT2_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT2_RXBUFRESET_IN,
    output  [2:0]   GT2_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT2_RXDFEAGCHOLD_IN,
    input           GT2_RXDFELPMRESET_IN,
    output  [6:0]   GT2_RXMONITOROUT_OUT,
    input   [1:0]   GT2_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT2_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT2_RXDATAVALID_OUT,
    output  [1:0]   GT2_RXHEADER_OUT,
    output          GT2_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT2_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT2_GTRXRESET_IN,
    input           GT2_RXPCSRESET_IN,
    input           GT2_RXPMARESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT2_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT2_GTTXRESET_IN,
    input           GT2_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT2_TXUSRCLK_IN,
    input           GT2_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT2_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT2_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT2_GTXTXN_OUT,
    output          GT2_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT2_TXOUTCLK_OUT,
    output          GT2_TXOUTCLKFABRIC_OUT,
    output          GT2_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT2_TXHEADER_IN,
    input   [6:0]   GT2_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT2_TXPCSRESET_IN,
    output          GT2_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT2_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y11)
    //____________________________CHANNEL PORTS________________________________
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT3_DRPADDR_IN,
    input           GT3_DRPCLK_IN,
    input   [15:0]  GT3_DRPDI_IN,
    output  [15:0]  GT3_DRPDO_OUT,
    input           GT3_DRPEN_IN,
    output          GT3_DRPRDY_OUT,
    input           GT3_DRPWE_IN,
    //----------------------------- Loopback Ports -----------------------------
    input   [2:0]   GT3_LOOPBACK_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT3_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT3_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT3_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT3_RXUSRCLK_IN,
    input           GT3_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT3_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT3_RXPRBSERR_OUT,
    input   [2:0]   GT3_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT3_RXPRBSCNTRESET_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT3_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT3_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT3_RXBUFRESET_IN,
    output  [2:0]   GT3_RXBUFSTATUS_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT3_RXDFEAGCHOLD_IN,
    input           GT3_RXDFELPMRESET_IN,
    output  [6:0]   GT3_RXMONITOROUT_OUT,
    input   [1:0]   GT3_RXMONITORSEL_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT3_RXOUTCLK_OUT,
    //-------------------- Receive Ports - RX Gearbox Ports --------------------
    output          GT3_RXDATAVALID_OUT,
    output  [1:0]   GT3_RXHEADER_OUT,
    output          GT3_RXHEADERVALID_OUT,
    //------------------- Receive Ports - RX Gearbox Ports  --------------------
    input           GT3_RXGEARBOXSLIP_IN,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT3_GTRXRESET_IN,
    input           GT3_RXPCSRESET_IN,
    input           GT3_RXPMARESET_IN,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT3_RXRESETDONE_OUT,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT3_GTTXRESET_IN,
    input           GT3_TXUSERRDY_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT3_TXUSRCLK_IN,
    input           GT3_TXUSRCLK2_IN,
    //------------------- Transmit Ports - PCI Express Ports -------------------
    input           GT3_TXELECIDLE_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT3_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT3_GTXTXN_OUT,
    output          GT3_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT3_TXOUTCLK_OUT,
    output          GT3_TXOUTCLKFABRIC_OUT,
    output          GT3_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [1:0]   GT3_TXHEADER_IN,
    input   [6:0]   GT3_TXSEQUENCE_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT3_TXPCSRESET_IN,
    output          GT3_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT3_TXPRBSSEL_IN,


    //____________________________COMMON PORTS________________________________
    //-------------------- Common Block  - Ref Clock Ports ---------------------
    input           GT0_GTREFCLK0_COMMON_IN,
    //----------------------- Common Block - QPLL Ports ------------------------
    output          GT0_QPLLLOCK_OUT,
    input           GT0_QPLLLOCKDETCLK_IN,
    output          GT0_QPLLREFCLKLOST_OUT,
    input           GT0_QPLLRESET_IN


);
//***************************** Parameter Declarations ************************
    parameter QPLL_FBDIV_TOP =  80;

    parameter QPLL_FBDIV_IN  =  (QPLL_FBDIV_TOP == 16)  ? 10'b0000100000 : 
				(QPLL_FBDIV_TOP == 20)  ? 10'b0000110000 :
				(QPLL_FBDIV_TOP == 32)  ? 10'b0001100000 :
				(QPLL_FBDIV_TOP == 40)  ? 10'b0010000000 :
				(QPLL_FBDIV_TOP == 64)  ? 10'b0011100000 :
				(QPLL_FBDIV_TOP == 66)  ? 10'b0101000000 :
				(QPLL_FBDIV_TOP == 80)  ? 10'b0100100000 :
				(QPLL_FBDIV_TOP == 100) ? 10'b0101110000 : 10'b0000000000;

   parameter QPLL_FBDIV_RATIO = (QPLL_FBDIV_TOP == 16)  ? 1'b1 : 
				(QPLL_FBDIV_TOP == 20)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 32)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 40)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 64)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 66)  ? 1'b0 :
				(QPLL_FBDIV_TOP == 80)  ? 1'b1 :
				(QPLL_FBDIV_TOP == 100) ? 1'b1 : 1'b1;

//***************************** Wire Declarations *****************************

    // ground and vcc signals
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [63:0]  tied_to_vcc_vec_i;
    
    wire            gt0_qplloutclk_i;
    wire            gt0_qplloutrefclk_i;

    wire            gt0_qpllclk_i;
    wire            gt0_qpllrefclk_i;

    wire            gt1_qpllclk_i;
    wire            gt1_qpllrefclk_i;

    wire            gt2_qpllclk_i;
    wire            gt2_qpllrefclk_i;

    wire            gt3_qpllclk_i;
    wire            gt3_qpllrefclk_i;

         
//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


    assign  gt0_qpllclk_i    = gt0_qplloutclk_i;  
    assign  gt0_qpllrefclk_i = gt0_qplloutrefclk_i; 
    assign  gt1_qpllclk_i    = gt0_qplloutclk_i;  
    assign  gt1_qpllrefclk_i = gt0_qplloutrefclk_i; 
    assign  gt2_qpllclk_i    = gt0_qplloutclk_i;  
    assign  gt2_qpllrefclk_i = gt0_qplloutrefclk_i; 
    assign  gt3_qpllclk_i    = gt0_qplloutclk_i;  
    assign  gt3_qpllrefclk_i = gt0_qplloutrefclk_i; 
      
      
 
//------------------------- GT Instances  -------------------------------
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y8)

    ip_gtwizard_v2_4_1x_4ch_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt0_ip_gtwizard_v2_4_1x_4ch_i
    (
        .tx_polarity_set_in				 (1'b0),
		  //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT0_DRPADDR_IN),
        .DRPCLK_IN                      (GT0_DRPCLK_IN),
        .DRPDI_IN                       (GT0_DRPDI_IN),
        .DRPDO_OUT                      (GT0_DRPDO_OUT),
        .DRPEN_IN                       (GT0_DRPEN_IN),
        .DRPRDY_OUT                     (GT0_DRPRDY_OUT),
        .DRPWE_IN                       (GT0_DRPWE_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (gt0_qpllclk_i),
        .QPLLREFCLK_IN                  (gt0_qpllrefclk_i),
        //----------------------------- Loopback Ports -----------------------------
        .LOOPBACK_IN                    (GT0_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT0_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANDATAERROR_OUT           (GT0_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT0_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT0_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT0_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT0_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT0_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT0_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT0_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT0_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT0_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT0_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT0_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFEAGCHOLD_IN                (GT0_RXDFEAGCHOLD_IN),
        .RXDFELPMRESET_IN               (GT0_RXDFELPMRESET_IN),
        .RXMONITOROUT_OUT               (GT0_RXMONITOROUT_OUT),
        .RXMONITORSEL_IN                (GT0_RXMONITORSEL_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT0_RXOUTCLK_OUT),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .RXDATAVALID_OUT                (GT0_RXDATAVALID_OUT),
        .RXHEADER_OUT                   (GT0_RXHEADER_OUT),
        .RXHEADERVALID_OUT              (GT0_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .RXGEARBOXSLIP_IN               (GT0_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT0_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT0_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT0_RXPMARESET_IN),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT0_RXRESETDONE_OUT),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT0_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT0_TXUSERRDY_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT0_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT0_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (GT0_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT0_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT0_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT0_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT0_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT0_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT0_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXHEADER_IN                    (GT0_TXHEADER_IN),
        .TXSEQUENCE_IN                  (GT0_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT0_TXPCSRESET_IN),
        .TXRESETDONE_OUT                (GT0_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT0_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y9)

    ip_gtwizard_v2_4_1x_4ch_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt1_ip_gtwizard_v2_4_1x_4ch_i
    (
        .tx_polarity_set_in				 (1'b0),
		  //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT1_DRPADDR_IN),
        .DRPCLK_IN                      (GT1_DRPCLK_IN),
        .DRPDI_IN                       (GT1_DRPDI_IN),
        .DRPDO_OUT                      (GT1_DRPDO_OUT),
        .DRPEN_IN                       (GT1_DRPEN_IN),
        .DRPRDY_OUT                     (GT1_DRPRDY_OUT),
        .DRPWE_IN                       (GT1_DRPWE_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (gt1_qpllclk_i),
        .QPLLREFCLK_IN                  (gt1_qpllrefclk_i),
        //----------------------------- Loopback Ports -----------------------------
        .LOOPBACK_IN                    (GT1_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT1_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANDATAERROR_OUT           (GT1_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT1_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT1_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT1_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT1_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT1_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT1_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT1_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT1_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT1_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT1_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT1_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFEAGCHOLD_IN                (GT1_RXDFEAGCHOLD_IN),
        .RXDFELPMRESET_IN               (GT1_RXDFELPMRESET_IN),
        .RXMONITOROUT_OUT               (GT1_RXMONITOROUT_OUT),
        .RXMONITORSEL_IN                (GT1_RXMONITORSEL_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT1_RXOUTCLK_OUT),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .RXDATAVALID_OUT                (GT1_RXDATAVALID_OUT),
        .RXHEADER_OUT                   (GT1_RXHEADER_OUT),
        .RXHEADERVALID_OUT              (GT1_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .RXGEARBOXSLIP_IN               (GT1_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT1_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT1_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT1_RXPMARESET_IN),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT1_RXRESETDONE_OUT),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT1_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT1_TXUSERRDY_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT1_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT1_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (GT1_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT1_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT1_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT1_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT1_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT1_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT1_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXHEADER_IN                    (GT1_TXHEADER_IN),
        .TXSEQUENCE_IN                  (GT1_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT1_TXPCSRESET_IN),
        .TXRESETDONE_OUT                (GT1_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT1_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y10)

    ip_gtwizard_v2_4_1x_4ch_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt2_ip_gtwizard_v2_4_1x_4ch_i
    (
        .tx_polarity_set_in				 (1'b1),
		  //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT2_DRPADDR_IN),
        .DRPCLK_IN                      (GT2_DRPCLK_IN),
        .DRPDI_IN                       (GT2_DRPDI_IN),
        .DRPDO_OUT                      (GT2_DRPDO_OUT),
        .DRPEN_IN                       (GT2_DRPEN_IN),
        .DRPRDY_OUT                     (GT2_DRPRDY_OUT),
        .DRPWE_IN                       (GT2_DRPWE_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (gt2_qpllclk_i),
        .QPLLREFCLK_IN                  (gt2_qpllrefclk_i),
        //----------------------------- Loopback Ports -----------------------------
        .LOOPBACK_IN                    (GT2_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT2_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANDATAERROR_OUT           (GT2_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT2_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT2_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT2_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT2_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT2_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT2_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT2_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT2_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT2_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT2_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT2_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFEAGCHOLD_IN                (GT2_RXDFEAGCHOLD_IN),
        .RXDFELPMRESET_IN               (GT2_RXDFELPMRESET_IN),
        .RXMONITOROUT_OUT               (GT2_RXMONITOROUT_OUT),
        .RXMONITORSEL_IN                (GT2_RXMONITORSEL_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT2_RXOUTCLK_OUT),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .RXDATAVALID_OUT                (GT2_RXDATAVALID_OUT),
        .RXHEADER_OUT                   (GT2_RXHEADER_OUT),
        .RXHEADERVALID_OUT              (GT2_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .RXGEARBOXSLIP_IN               (GT2_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT2_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT2_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT2_RXPMARESET_IN),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT2_RXRESETDONE_OUT),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT2_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT2_TXUSERRDY_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT2_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT2_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (GT2_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT2_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT2_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT2_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT2_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT2_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT2_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXHEADER_IN                    (GT2_TXHEADER_IN),
        .TXSEQUENCE_IN                  (GT2_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT2_TXPCSRESET_IN),
        .TXRESETDONE_OUT                (GT2_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT2_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y11)

    ip_gtwizard_v2_4_1x_4ch_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt3_ip_gtwizard_v2_4_1x_4ch_i
    (
        .tx_polarity_set_in				 (1'b0),
		  //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT3_DRPADDR_IN),
        .DRPCLK_IN                      (GT3_DRPCLK_IN),
        .DRPDI_IN                       (GT3_DRPDI_IN),
        .DRPDO_OUT                      (GT3_DRPDO_OUT),
        .DRPEN_IN                       (GT3_DRPEN_IN),
        .DRPRDY_OUT                     (GT3_DRPRDY_OUT),
        .DRPWE_IN                       (GT3_DRPWE_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (gt3_qpllclk_i),
        .QPLLREFCLK_IN                  (gt3_qpllrefclk_i),
        //----------------------------- Loopback Ports -----------------------------
        .LOOPBACK_IN                    (GT3_LOOPBACK_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT3_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANDATAERROR_OUT           (GT3_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT3_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT3_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT3_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT3_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT3_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT3_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT3_RXPRBSCNTRESET_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT3_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT3_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT3_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT3_RXBUFSTATUS_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFEAGCHOLD_IN                (GT3_RXDFEAGCHOLD_IN),
        .RXDFELPMRESET_IN               (GT3_RXDFELPMRESET_IN),
        .RXMONITOROUT_OUT               (GT3_RXMONITOROUT_OUT),
        .RXMONITORSEL_IN                (GT3_RXMONITORSEL_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT3_RXOUTCLK_OUT),
        //-------------------- Receive Ports - RX Gearbox Ports --------------------
        .RXDATAVALID_OUT                (GT3_RXDATAVALID_OUT),
        .RXHEADER_OUT                   (GT3_RXHEADER_OUT),
        .RXHEADERVALID_OUT              (GT3_RXHEADERVALID_OUT),
        //------------------- Receive Ports - RX Gearbox Ports  --------------------
        .RXGEARBOXSLIP_IN               (GT3_RXGEARBOXSLIP_IN),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT3_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT3_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT3_RXPMARESET_IN),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT3_RXRESETDONE_OUT),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT3_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT3_TXUSERRDY_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT3_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT3_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (GT3_TXELECIDLE_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT3_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT3_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT3_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT3_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT3_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT3_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXHEADER_IN                    (GT3_TXHEADER_IN),
        .TXSEQUENCE_IN                  (GT3_TXSEQUENCE_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT3_TXPCSRESET_IN),
        .TXRESETDONE_OUT                (GT3_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT3_TXPRBSSEL_IN)

    );


    //_________________________________________________________________________
    //_________________________________________________________________________
    //_________________________GTXE2_COMMON____________________________________

    GTXE2_COMMON #
    (
            // Simulation attributes
            .SIM_RESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
            .SIM_QPLLREFCLK_SEL  (3'b001),
            .SIM_VERSION         (SIM_VERSION),


           //----------------COMMON BLOCK Attributes---------------
            .BIAS_CFG                               (64'h0000040000001000),
            .COMMON_CFG                             (32'h00000000),
            .QPLL_CFG                               (27'h0680181),
            .QPLL_CLKOUT_CFG                        (4'b0000),
            .QPLL_COARSE_FREQ_OVRD                  (6'b010000),
            .QPLL_COARSE_FREQ_OVRD_EN               (1'b0),
            .QPLL_CP                                (10'b0000011111),
            .QPLL_CP_MONITOR_EN                     (1'b0),
            .QPLL_DMONITOR_SEL                      (1'b0),
            .QPLL_FBDIV                             (QPLL_FBDIV_IN),
            .QPLL_FBDIV_MONITOR_EN                  (1'b0),
            .QPLL_FBDIV_RATIO                       (QPLL_FBDIV_RATIO),
            .QPLL_INIT_CFG                          (24'h000006),
            .QPLL_LOCK_CFG                          (16'h21E8),
            .QPLL_LPF                               (4'b1111),
            .QPLL_REFCLK_DIV                        (1)

    )
    gtxe2_common_0_i
    (
        //----------- Common Block  - Dynamic Reconfiguration Port (DRP) -----------
        .DRPADDR                        (tied_to_ground_vec_i[7:0]),
        .DRPCLK                         (tied_to_ground_i),
        .DRPDI                          (tied_to_ground_vec_i[15:0]),
        .DRPDO                          (),
        .DRPEN                          (tied_to_ground_i),
        .DRPRDY                         (),
        .DRPWE                          (tied_to_ground_i),
        //-------------------- Common Block  - Ref Clock Ports ---------------------
        .GTGREFCLK                      (tied_to_ground_i),
        .GTNORTHREFCLK0                 (tied_to_ground_i),
        .GTNORTHREFCLK1                 (tied_to_ground_i),
        .GTREFCLK0                      (GT0_GTREFCLK0_COMMON_IN),
        .GTREFCLK1                      (tied_to_ground_i),
        .GTSOUTHREFCLK0                 (tied_to_ground_i),
        .GTSOUTHREFCLK1                 (tied_to_ground_i),
        //----------------------- Common Block -  QPLL Ports -----------------------
        .QPLLDMONITOR                   (),
        //--------------------- Common Block - Clocking Ports ----------------------
        .QPLLOUTCLK                     (gt0_qplloutclk_i),
        .QPLLOUTREFCLK                  (gt0_qplloutrefclk_i),
        .REFCLKOUTMONITOR               (),
        //----------------------- Common Block - QPLL Ports ------------------------
        .QPLLFBCLKLOST                  (),
        .QPLLLOCK                       (GT0_QPLLLOCK_OUT),
        .QPLLLOCKDETCLK                 (GT0_QPLLLOCKDETCLK_IN),
        .QPLLLOCKEN                     (tied_to_vcc_i),
        .QPLLOUTRESET                   (tied_to_ground_i),
        .QPLLPD                         (tied_to_ground_i),
        .QPLLREFCLKLOST                 (GT0_QPLLREFCLKLOST_OUT),
        .QPLLREFCLKSEL                  (3'b001),
        .QPLLRESET                      (GT0_QPLLRESET_IN),
        .QPLLRSVD1                      (16'b0000000000000000),
        .QPLLRSVD2                      (5'b11111),
        //------------------------------- QPLL Ports -------------------------------
        .BGBYPASSB                      (tied_to_vcc_i),
        .BGMONITORENB                   (tied_to_vcc_i),
        .BGPDB                          (tied_to_vcc_i),
        .BGRCALOVRD                     (5'b00000),
        .PMARSVD                        (8'b00000000),
        .RCALENB                        (tied_to_vcc_i)

    );




endmodule

    
