////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 3.6
//  \   \         Application : 7 Series FPGAs Transceivers Wizard 
//  /   /         Filename : gtwizard_0_exdes.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module gtwizard_0_exdes
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1

(* DowngradeIPIdentifiedWarnings="yes" *)
//***********************************Entity Declaration************************
(* CORE_GENERATION_INFO = "gtwizard_0,gtwizard_v3_6_8,{protocol_file=srio_gen2_single_lane}" *)
module gtwizard_0_exdes #
(
    parameter EXAMPLE_CONFIG_INDEPENDENT_LANES     =   1,//configuration for frame gen and check
    parameter EXAMPLE_LANE_WITH_START_CHAR         =   0,         // specifies lane with unique start frame char
    parameter EXAMPLE_WORDS_IN_BRAM                =   512,       // specifies amount of data in BRAM
    parameter EXAMPLE_SIM_GTRESET_SPEEDUP          =   "TRUE",    // simulation setting for GT SecureIP model
    parameter EXAMPLE_USE_CHIPSCOPE                =   0,         // Set to 1 to use Chipscope to drive resets
    parameter STABLE_CLOCK_PERIOD                  = 20

)
(
    input wire  Q2_CLK1_GTREFCLK_PAD_N_IN,
    input wire  Q2_CLK1_GTREFCLK_PAD_P_IN,
    input wire  CLK_IN_50M,
    output wire TRACK_DATA_OUT,
    input  wire         RXN_IN,
    input  wire         RXP_IN,
    output wire         TXN_OUT,
    output wire         TXP_OUT,
    input  wire         ad9516_ld_in,
    output wire         ad9516_cs_n_out,
    output wire         ad9516_sclk_out,
    output wire         ad9516_sdata_out,
    output wire         ad9516_refsel_out,
    output wire         ad9516_pdwn_out,
    output wire         ad9516_rstn_out,
    output wire         ad9516_syn_n_out,
    output wire         DBG_GT0_CPLLLOCK,
    output wire         DBG_GT0_CPLLFBCLKLOST,
    output wire         DBG_GT0_TXRESETDONE,
    output wire         DBG_GT0_TXFSMRESETDONE,
    output wire         DBG_GT0_TX_SYSTEM_RESET,
    output wire         DBG_GT0_TXUSERRDY,
    output wire         DBG_GT0_GTTXRESET,
    output wire         DBG_GT0_TXPMARESET,
    output wire         DBG_GT0_TXPCSRESET,
    output wire [31:0]  DBG_GT0_TXDATA,
    output wire [3:0]   DBG_GT0_TXCHARISK,
    output wire [8:0]   DBG_GT0_TX_READ_COUNTER,
    output wire         DBG_GT0_TXUSRCLK2,
    output wire         DBG_GT0_RXRESETDONE,
    output wire         DBG_GT0_RXFSMRESETDONE,
    output wire         DBG_GT0_RX_SYSTEM_RESET,
    output wire         DBG_GT0_RXUSERRDY,
    output wire         DBG_GT0_GTRXRESET,
    output wire         DBG_GT0_RXPMARESET,
    output wire         DBG_GT0_RXPCSRESET,
    output wire [31:0]  DBG_GT0_RXDATA,
    output wire [3:0]   DBG_GT0_RXCHARISK,
    output wire [7:0]   DBG_GT0_ERROR_COUNT,
    output wire         DBG_GT0_TRACK_DATA,
    output wire [3:0]   DBG_GT0_RXDISPERR,
    output wire [3:0]   DBG_GT0_RXNOTINTABLE,
    output wire         DBG_GT0_RXBYTEISALIGNED,
    output wire         DBG_GT0_RXBYTEREALIGN,
    output wire         DBG_GT0_RXCOMMADET,
    output wire         DBG_GT0_RXMCOMMAALIGNEN,
    output wire         DBG_GT0_RXPCOMMAALIGNEN,
    output wire [1:0]   DBG_GT0_RXCLKCORCNT,
    output wire [31:0]  DBG_GT0_RXDATA_ALIGNED,
    output wire [31:0]  DBG_GT0_RXDATA_TRACK,
    output wire [1:0]   DBG_GT0_RXALIGN_SEL,
    output wire         DBG_GT0_RXSTART_OF_PACKET,
    output wire         DBG_GT0_RXUSRCLK2,
    output wire [31:0]  DBG_HV_PACKET_OUT,
    output wire [15:0]  DBG_HV_CURRENT_ADDR,
    output wire         DBG_HV_PACKET_VALID,
    output wire         DBG_HV_USING_INTERNAL_SOURCE,
    output wire [31:0]  DBG_HV_RX_PACKET_OUT,
    output wire [15:0]  DBG_HV_RX_CURRENT_ADDR,
    output wire [15:0]  DBG_HV_RX_CURRENT_DATA,
    output wire [15:0]  DBG_HV_RX_EXPECTED_ADDR,
    output wire         DBG_HV_RX_PACKET_SEEN,
    output wire         DBG_HV_RX_ADDR_IN_RANGE,
    output wire         DBG_HV_RX_SEQ_LOCKED,
    output wire         DBG_HV_RX_SEQ_OK,
    output wire         DBG_HV_RX_INVALID_FILL,
    output wire [7:0]   DBG_HV_RX_SEQ_ERROR_COUNT,
    output wire         DBG_SOFT_RESET,
    output wire         DBG_DRPCLK_HEARTBEAT
);

    wire soft_reset_i;
    (*mark_debug = "TRUE" *) wire soft_reset_vio_i;

//************************** Register Declarations ****************************

    wire            gt_txfsmresetdone_i;
    wire            gt_rxfsmresetdone_i;
    (* ASYNC_REG = "TRUE" *)reg             gt_txfsmresetdone_r;
    (* ASYNC_REG = "TRUE" *)reg             gt_txfsmresetdone_r2;
    wire            gt0_txfsmresetdone_i;
    wire            gt0_rxfsmresetdone_i;
    (* ASYNC_REG = "TRUE" *)reg             gt0_txfsmresetdone_r;
    (* ASYNC_REG = "TRUE" *)reg             gt0_txfsmresetdone_r2;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxfsmresetdone_r;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxfsmresetdone_r2;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_r;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_r2;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_r3;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_vio_r;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_vio_r2;
    (* ASYNC_REG = "TRUE" *)reg             gt0_rxresetdone_vio_r3;

    reg [5:0] reset_counter = 0;
    reg     [3:0]   reset_pulse;
    reg     [25:0]  drpclk_heartbeat_cnt = 26'd0;

//**************************** Wire Declarations ******************************//
    //------------------------ GT Wrapper Wires ------------------------------
    //________________________________________________________________________
    //________________________________________________________________________
    //GT0  (X1Y0)
    //------------------------------- CPLL Ports -------------------------------
    wire            gt0_cpllfbclklost_i;
    wire            gt0_cplllock_i;
    wire            gt0_cpllrefclklost_i;
    wire            gt0_cpllreset_i;
    //-------------------------- Channel - DRP Ports  --------------------------
    wire    [8:0]   gt0_drpaddr_i;
    wire    [15:0]  gt0_drpdi_i;
    wire    [15:0]  gt0_drpdo_i;
    wire            gt0_drpen_i;
    wire            gt0_drprdy_i;
    wire            gt0_drpwe_i;
    //------------------------- Digital Monitor Ports --------------------------
    wire    [7:0]   gt0_dmonitorout_i;
    //----------------------------- Loopback Ports -----------------------------
    wire    [2:0]   gt0_loopback_i;
    //---------------------------- Power-Down Ports ----------------------------
    wire    [1:0]   gt0_rxpd_i;
    wire    [1:0]   gt0_txpd_i;
    //------------------- RX Initialization and Reset Ports --------------------
    wire            gt0_eyescanreset_i;
    wire            gt0_rxuserrdy_i;
    //------------------------ RX Margin Analysis Ports ------------------------
    wire            gt0_eyescandataerror_i;
    wire            gt0_eyescantrigger_i;
    //----------------------- Receive Ports - CDR Ports ------------------------
    wire            gt0_rxcdrhold_i;
    //----------------- Receive Ports - Clock Correction Ports -----------------
    wire    [1:0]   gt0_rxclkcorcnt_i;
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    wire    [31:0]  gt0_rxdata_i;
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    wire            gt0_rxprbserr_i;
    wire    [2:0]   gt0_rxprbssel_i;
    //----------------- Receive Ports - Pattern Checker ports ------------------
    wire            gt0_rxprbscntreset_i;
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
    wire    [3:0]   gt0_rxdisperr_i;
    wire    [3:0]   gt0_rxnotintable_i;
    //------------------------- Receive Ports - RX AFE -------------------------
    wire            gt0_gtxrxp_i;
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    wire            gt0_gtxrxn_i;
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    wire            gt0_rxbufreset_i;
    wire    [2:0]   gt0_rxbufstatus_i;
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    wire            gt0_rxbyteisaligned_i;
    wire            gt0_rxbyterealign_i;
    wire            gt0_rxcommadet_i;
    wire            gt0_rxmcommaalignen_i;
    wire            gt0_rxpcommaalignen_i;
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    wire            gt0_rxdfelpmreset_i;
    wire    [6:0]   gt0_rxmonitorout_i;
    wire    [1:0]   gt0_rxmonitorsel_i;
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    wire            gt0_rxoutclk_i;
    wire            gt0_rxoutclkfabric_i;
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    wire            gt0_gtrxreset_i;
    wire            gt0_rxpcsreset_i;
    wire            gt0_rxpmareset_i;
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
    wire            gt0_rxlpmen_i;
    //--------------- Receive Ports - RX Polarity Control Ports ----------------
    wire            gt0_rxpolarity_i;
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    wire    [3:0]   gt0_rxchariscomma_i;
    wire    [3:0]   gt0_rxcharisk_i;
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    wire            gt0_rxresetdone_i;
    //---------------------- TX Configurable Driver Ports ----------------------
    wire    [4:0]   gt0_txpostcursor_i;
    wire    [4:0]   gt0_txprecursor_i;
    //------------------- TX Initialization and Reset Ports --------------------
    wire            gt0_gttxreset_i;
    wire            gt0_txuserrdy_i;
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
    wire            gt0_txprbsforceerr_i;
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
    wire    [1:0]   gt0_txbufstatus_i;
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    wire    [3:0]   gt0_txdiffctrl_i;
    wire            gt0_txinhibit_i;
    wire    [6:0]   gt0_txmaincursor_i;
    //---------------- Transmit Ports - TX Data Path interface -----------------
    wire    [31:0]  gt0_txdata_i;
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    wire            gt0_gtxtxn_i;
    wire            gt0_gtxtxp_i;
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    wire            gt0_txoutclk_i;
    wire            gt0_txoutclkfabric_i;
    wire            gt0_txoutclkpcs_i;
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    wire    [3:0]   gt0_txcharisk_i;
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    wire            gt0_txpcsreset_i;
    wire            gt0_txpmareset_i;
    wire            gt0_txresetdone_i;
    //--------------- Transmit Ports - TX Polarity Control Ports ---------------
    wire            gt0_txpolarity_i;
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    wire    [2:0]   gt0_txprbssel_i;

    //____________________________COMMON PORTS________________________________
    //-------------------- Common Block  - Ref Clock Ports ---------------------
    wire            gt0_gtrefclk1_common_i;
    //----------------------- Common Block - QPLL Ports ------------------------
    wire            gt0_qplllock_i;
    wire            gt0_qpllrefclklost_i;
    wire            gt0_qpllreset_i;


    //----------------------------- Global Signals -----------------------------

    wire            drpclk_in_i;
    wire            cfgmclk_raw_i;
    wire            debug_clk_i;
    wire            gt0_tx_system_reset_c;
    wire            gt0_rx_system_reset_c;
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [7:0]   tied_to_vcc_vec_i;
    wire            GTTXRESET_IN;
    wire            GTRXRESET_IN;
    wire            CPLLRESET_IN;
    wire            QPLLRESET_IN;

     //--------------------------- User Clocks ---------------------------------
     wire            gt0_txusrclk_i; 
     wire            gt0_txusrclk2_i; 
     wire            gt0_rxusrclk_i; 
     wire            gt0_rxusrclk2_i; 
 
    //--------------------------- Reference Clocks ----------------------------
    
    wire            q2_clk1_refclk_i;


    //--------------------- Frame check/gen Module Signals --------------------
    wire            gt0_matchn_i;
    
    wire    [3:0]   gt0_txcharisk_float_i;
   
    wire    [15:0]  gt0_txdata_float16_i;
    wire    [31:0]  gt0_txdata_float_i;
    wire    [79:0]  gt0_frame_gen_data_i;
    wire    [7:0]   gt0_frame_gen_ctrl_i;
    wire    [8:0]   gt0_tx_read_counter_i;
    wire    [31:0]  gt0_hv_packet_i;
    wire            gt0_hv_packet_valid_i;
    wire    [15:0]  gt0_hv_current_addr_i;
    wire            gt0_hv_using_internal_i;
    wire    [15:0]  gt0_hv_external_data_i;
    wire            gt0_hv_external_valid_i;
    wire    [31:0]  gt0_hv_rx_packet_i;
    wire    [15:0]  gt0_hv_rx_current_addr_i;
    wire    [15:0]  gt0_hv_rx_current_data_i;
    wire    [15:0]  gt0_hv_rx_expected_addr_i;
    wire            gt0_hv_rx_packet_seen_i;
    wire            gt0_hv_rx_addr_in_range_i;
    wire            gt0_hv_rx_seq_locked_i;
    wire            gt0_hv_rx_seq_ok_i;
    wire            gt0_hv_rx_invalid_fill_i;
    wire    [7:0]   gt0_hv_rx_seq_error_count_i;
    wire            gt0_hv_rx_packet_valid_i;
    
    
    wire            gt0_block_sync_i;
    wire            gt0_track_data_i;
    wire    [7:0]   gt0_error_count_i;
    wire            gt0_frame_check_reset_i;
    wire            gt0_inc_in_i;
    wire            gt0_inc_out_i;
    wire    [31:0]  gt0_unscrambled_data_i;
    wire    [31:0]  gt0_rxdata_aligned_dbg_i;
    wire    [31:0]  gt0_rxdata_track_dbg_i;
    wire    [1:0]   gt0_rxalign_sel_dbg_i;
    wire            gt0_rxstart_of_packet_dbg_i;

    wire            reset_on_data_error_i;
    wire            track_data_out_i;
    wire            DRP_CLK_IN;
    wire            lock;
    reg     [19:0]  cnt_0 = 20'd0;
    reg             trig_ad9516 = 1'b0;
  
    assign gt0_hv_external_data_i  = 16'h0000;
    assign gt0_hv_external_valid_i = 1'b0;

    //--------------------- Chipscope Signals ---------------------------------
    (*mark_debug = "TRUE" *)wire   rxresetdone_vio_i;
    wire    [35:0]  tx_data_vio_control_i;
    wire    [35:0]  rx_data_vio_control_i;
    wire    [35:0]  shared_vio_control_i;
    wire    [35:0]  ila_control_i;
    wire    [35:0]  channel_drp_vio_control_i;
    wire    [35:0]  common_drp_vio_control_i;
    wire    [31:0]  tx_data_vio_async_in_i;
    wire    [31:0]  tx_data_vio_sync_in_i;
    wire    [31:0]  tx_data_vio_async_out_i;
    wire    [31:0]  tx_data_vio_sync_out_i;
    wire    [31:0]  rx_data_vio_async_in_i;
    wire    [31:0]  rx_data_vio_sync_in_i;
    wire    [31:0]  rx_data_vio_async_out_i;
    wire    [31:0]  rx_data_vio_sync_out_i;
    wire    [31:0]  shared_vio_in_i;
    wire    [31:0]  shared_vio_out_i;
    wire    [163:0] ila_in_i;
    wire    [31:0]  channel_drp_vio_async_in_i;
    wire    [31:0]  channel_drp_vio_sync_in_i;
    wire    [31:0]  channel_drp_vio_async_out_i;
    wire    [31:0]  channel_drp_vio_sync_out_i;
    wire    [31:0]  common_drp_vio_async_in_i;
    wire    [31:0]  common_drp_vio_sync_in_i;
    wire    [31:0]  common_drp_vio_async_out_i;
    wire    [31:0]  common_drp_vio_sync_out_i;

    wire    [31:0]  gt0_tx_data_vio_async_in_i;
    wire    [31:0]  gt0_tx_data_vio_sync_in_i;
    wire    [31:0]  gt0_tx_data_vio_async_out_i;
    wire    [31:0]  gt0_tx_data_vio_sync_out_i;
    wire    [31:0]  gt0_rx_data_vio_async_in_i;
    wire    [31:0]  gt0_rx_data_vio_sync_in_i;
    wire    [31:0]  gt0_rx_data_vio_async_out_i;
    wire    [31:0]  gt0_rx_data_vio_sync_out_i;
    wire    [163:0] gt0_ila_in_i;
    wire    [31:0]  gt0_channel_drp_vio_async_in_i;
    wire    [31:0]  gt0_channel_drp_vio_sync_in_i;
    wire    [31:0]  gt0_channel_drp_vio_async_out_i;
    wire    [31:0]  gt0_channel_drp_vio_sync_out_i;
    wire    [31:0]  gt0_common_drp_vio_async_in_i;
    wire    [31:0]  gt0_common_drp_vio_sync_in_i;
    wire    [31:0]  gt0_common_drp_vio_async_out_i;
    wire    [31:0]  gt0_common_drp_vio_sync_out_i;


    wire            gttxreset_i;
    wire            gtrxreset_i;

    wire            user_tx_reset_i;
    wire            user_rx_reset_i;
    wire            tx_vio_clk_i;
    wire            tx_vio_clk_mux_out_i;    
    wire            rx_vio_ila_clk_i;
    wire            rx_vio_ila_clk_mux_out_i;

    wire            cpllreset_i;
    


  wire [(80 -32) -1:0] zero_vector_rx_80 ;
  wire [(8 -4) -1:0] zero_vector_rx_8 ;
  wire [79:0] gt0_rxdata_ila ;
  wire [1:0]  gt0_rxdatavalid_ila; 
  wire [7:0]  gt0_rxcharisk_ila ;
  wire gt0_txmmcm_lock_ila ;
  wire gt0_rxmmcm_lock_ila ;
  wire gt0_rxresetdone_ila ;
  wire gt0_txresetdone_ila ;

//**************************** Main Body of Code *******************************

    //  Static signal Assigments    
    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 8'hff;

    assign zero_vector_rx_80 = 0;
    assign zero_vector_rx_8 = 0;

    
    //***********************************************************************//
    //                                                                       //
    //--------------------------- The GT Wrapper ----------------------------//
    //                                                                       //
    //***********************************************************************//
    
    // Use the instantiation template in the example directory to add the GT wrapper to your design.
    // In this example, the wrapper is wired up for basic operation with a frame generator and frame 
    // checker. The GTs will reset, then attempt to align and transmit data. If channel bonding is 
    // enabled, bonding should occur after alignment.
    // While connecting the GT TX/RX Reset ports below, please add a delay of
    // minimum 500ns as mentioned in AR 43482.

    
    gtwizard_0_support #
    (
        .EXAMPLE_SIM_GTRESET_SPEEDUP    (EXAMPLE_SIM_GTRESET_SPEEDUP),
        .STABLE_CLOCK_PERIOD            (STABLE_CLOCK_PERIOD)
    )
    gtwizard_0_support_i
    (
        .soft_reset_tx_in               (soft_reset_i),
        .soft_reset_rx_in               (soft_reset_i),
        .dont_reset_on_data_error_in    (tied_to_ground_i),
    .q2_clk1_gtrefclk_pad_n_in(Q2_CLK1_GTREFCLK_PAD_N_IN),
    .q2_clk1_gtrefclk_pad_p_in(Q2_CLK1_GTREFCLK_PAD_P_IN),
        .gt0_tx_fsm_reset_done_out      (gt0_txfsmresetdone_i),
        .gt0_rx_fsm_reset_done_out      (gt0_rxfsmresetdone_i),
        .gt0_data_valid_in              (gt0_track_data_i),
 
    .gt0_txusrclk_out(gt0_txusrclk_i),
    .gt0_txusrclk2_out(gt0_txusrclk2_i),
    .gt0_rxusrclk_out(gt0_rxusrclk_i),
    .gt0_rxusrclk2_out(gt0_rxusrclk2_i),


        //_____________________________________________________________________
        //_____________________________________________________________________
        //GT0  (X1Y0)

        //------------------------------- CPLL Ports -------------------------------
        .gt0_cpllfbclklost_out          (gt0_cpllfbclklost_i),
        .gt0_cplllock_out               (gt0_cplllock_i),
        .gt0_cpllreset_in               (tied_to_ground_i),
        //-------------------------- Channel - DRP Ports  --------------------------
        .gt0_drpaddr_in                 (gt0_drpaddr_i),
        .gt0_drpdi_in                   (gt0_drpdi_i),
        .gt0_drpdo_out                  (gt0_drpdo_i),
        .gt0_drpen_in                   (gt0_drpen_i),
        .gt0_drprdy_out                 (gt0_drprdy_i),
        .gt0_drpwe_in                   (gt0_drpwe_i),
        //------------------------- Digital Monitor Ports --------------------------
        .gt0_dmonitorout_out            (gt0_dmonitorout_i),
        //----------------------------- Loopback Ports -----------------------------
        .gt0_loopback_in                (gt0_loopback_i),
        //---------------------------- Power-Down Ports ----------------------------
        .gt0_rxpd_in                    (gt0_rxpd_i),
        .gt0_txpd_in                    (gt0_txpd_i),
        //------------------- RX Initialization and Reset Ports --------------------
        .gt0_eyescanreset_in            (tied_to_ground_i),
        .gt0_rxuserrdy_in               (gt0_rxuserrdy_i),
        //------------------------ RX Margin Analysis Ports ------------------------
        .gt0_eyescandataerror_out       (gt0_eyescandataerror_i),
        .gt0_eyescantrigger_in          (tied_to_ground_i),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .gt0_rxcdrhold_in               (gt0_rxcdrhold_i),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .gt0_rxclkcorcnt_out            (gt0_rxclkcorcnt_i),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt0_rxdata_out                 (gt0_rxdata_i),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .gt0_rxprbserr_out              (gt0_rxprbserr_i),
        .gt0_rxprbssel_in               (gt0_rxprbssel_i),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .gt0_rxprbscntreset_in          (gt0_rxprbscntreset_i),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .gt0_rxdisperr_out              (gt0_rxdisperr_i),
        .gt0_rxnotintable_out           (gt0_rxnotintable_i),
        //------------------------- Receive Ports - RX AFE -------------------------
        .gt0_gtxrxp_in                  (RXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt0_gtxrxn_in                  (RXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .gt0_rxbufreset_in              (gt0_rxbufreset_i),
        .gt0_rxbufstatus_out            (gt0_rxbufstatus_i),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .gt0_rxbyteisaligned_out        (gt0_rxbyteisaligned_i),
        .gt0_rxbyterealign_out          (gt0_rxbyterealign_i),
        .gt0_rxcommadet_out             (gt0_rxcommadet_i),
        .gt0_rxmcommaalignen_in         (gt0_rxmcommaalignen_i),
        .gt0_rxpcommaalignen_in         (gt0_rxpcommaalignen_i),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt0_rxdfelpmreset_in           (tied_to_ground_i),
        .gt0_rxmonitorout_out           (gt0_rxmonitorout_i),
        .gt0_rxmonitorsel_in            (2'b00),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt0_rxoutclkfabric_out         (gt0_rxoutclkfabric_i),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt0_gtrxreset_in               (gt0_gtrxreset_i),
        .gt0_rxpcsreset_in              (gt0_rxpcsreset_i),
        .gt0_rxpmareset_in              (gt0_rxpmareset_i),
        //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .gt0_rxlpmen_in                 (gt0_rxlpmen_i),
        //--------------- Receive Ports - RX Polarity Control Ports ----------------
        .gt0_rxpolarity_in              (gt0_rxpolarity_i),
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .gt0_rxchariscomma_out          (gt0_rxchariscomma_i),
        .gt0_rxcharisk_out              (gt0_rxcharisk_i),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt0_rxresetdone_out            (gt0_rxresetdone_i),
        //---------------------- TX Configurable Driver Ports ----------------------
        .gt0_txpostcursor_in            (gt0_txpostcursor_i),
        .gt0_txprecursor_in             (gt0_txprecursor_i),
        //------------------- TX Initialization and Reset Ports --------------------
        .gt0_gttxreset_in               (gt0_gttxreset_i),
        .gt0_txuserrdy_in               (gt0_txuserrdy_i),
        //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .gt0_txprbsforceerr_in          (gt0_txprbsforceerr_i),
        //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .gt0_txbufstatus_out            (gt0_txbufstatus_i),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .gt0_txdiffctrl_in              (gt0_txdiffctrl_i),
        .gt0_txinhibit_in               (gt0_txinhibit_i),
        .gt0_txmaincursor_in            (7'b0000000),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt0_txdata_in                  (gt0_txdata_i),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt0_gtxtxn_out                 (TXN_OUT),
        .gt0_gtxtxp_out                 (TXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt0_txoutclkfabric_out         (gt0_txoutclkfabric_i),
        .gt0_txoutclkpcs_out            (gt0_txoutclkpcs_i),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .gt0_txcharisk_in               (gt0_txcharisk_i),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt0_txpcsreset_in              (gt0_txpcsreset_i),
        .gt0_txpmareset_in              (gt0_txpmareset_i),
        .gt0_txresetdone_out            (gt0_txresetdone_i),
        //--------------- Transmit Ports - TX Polarity Control Ports ---------------
        .gt0_txpolarity_in              (gt0_txpolarity_i),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .gt0_txprbssel_in               (gt0_txprbssel_i),


    //____________________________COMMON PORTS________________________________
    .gt0_qplloutclk_out(),
    .gt0_qplloutrefclk_out(),
    .sysclk_in(DRP_CLK_IN)
    );

    ip_mmcme2_clk i_ip_mmcme2_clk
    (
        .CLK_IN1                        (CLK_IN_50M),
        .CLK_OUT1                       (DRP_CLK_IN),
        .CLK_OUT2                       (),
        .RESET                          (1'b0),
        .LOCKED                         (lock)
    );

    always @(posedge DRP_CLK_IN or negedge lock)
    begin
        if(!lock)
            cnt_0 <= 20'd0;
        else if(cnt_0 == 20'hF_FFFF)
            cnt_0 <= cnt_0;
        else
            cnt_0 <= cnt_0 + 1'b1;
    end

    always @(posedge DRP_CLK_IN or negedge lock)
    begin
        if(!lock)
            trig_ad9516 <= 1'b0;
        else if(cnt_0 == 20'h2_0000)
            trig_ad9516 <= 1'b1;
        else
            trig_ad9516 <= 1'b0;
    end

    m_ad9516_ctl i_m_ad9516_ctl
    (
        .clk_50m_in                     (DRP_CLK_IN),
        .rst_n                          (lock),
        .trig_in                        (trig_ad9516),
        .cs_n_out                       (ad9516_cs_n_out),
        .sclk_out                       (ad9516_sclk_out),
        .sdata_out                      (ad9516_sdata_out),
        .ad9516_refsel_out              (ad9516_refsel_out),
        .ad9516_pdwn_out                (ad9516_pdwn_out),
        .ad9516_rstn_out                (ad9516_rstn_out),
        .syn_n_out                      (ad9516_syn_n_out),
        .cfg_end_out                    ()
    );

    BUFG DRP_CLK_BUFG
    (
        .I                              (DRP_CLK_IN),
        .O                              (drpclk_in_i)
    );

    STARTUPE2 #(
        .PROG_USR("FALSE"),
        .SIM_CCLK_FREQ(0.0)
    ) STARTUPE2_DEBUG_CLK (
        .CFGCLK(),
        .CFGMCLK(cfgmclk_raw_i),
        .EOS(),
        .PREQ(),
        .CLK(1'b0),
        .GSR(1'b0),
        .GTS(1'b0),
        .KEYCLEARB(1'b1),
        .PACK(1'b0),
        .USRCCLKO(1'b0),
        .USRCCLKTS(1'b1),
        .USRDONEO(1'b1),
        .USRDONETS(1'b1)
    );

    BUFG DEBUG_CLK_BUFG
    (
        .I                              (cfgmclk_raw_i),
        .O                              (debug_clk_i)
    );

    always @(posedge drpclk_in_i)
    begin
        drpclk_heartbeat_cnt <= drpclk_heartbeat_cnt + 1'b1;
    end

 
    //***********************************************************************//
    //                                                                       //
    //--------------------------- User Module Resets-------------------------//
    //                                                                       //
    //***********************************************************************//
    // All the User Modules i.e. FRAME_GEN, FRAME_CHECK and the sync modules
    // are held in reset till the RESETDONE goes high. 
    // The RESETDONE is registered a couple of times on *USRCLK2 and connected 
    // to the reset of the modules
    
always @(posedge gt0_rxusrclk2_i or negedge gt0_rxresetdone_i)

    begin
        if (!gt0_rxresetdone_i)
        begin
            gt0_rxresetdone_r    <=   `DLY 1'b0;
            gt0_rxresetdone_r2   <=   `DLY 1'b0;
            gt0_rxresetdone_r3   <=   `DLY 1'b0;
        end
        else
        begin
            gt0_rxresetdone_r    <=   `DLY gt0_rxresetdone_i;
            gt0_rxresetdone_r2   <=   `DLY gt0_rxresetdone_r;
            gt0_rxresetdone_r3   <=   `DLY gt0_rxresetdone_r2;
        end
    end

    
    
always @(posedge  gt0_txusrclk2_i or negedge gt0_txfsmresetdone_i)

    begin
        if (!gt0_txfsmresetdone_i)
        begin
            gt0_txfsmresetdone_r    <=   `DLY 1'b0;
            gt0_txfsmresetdone_r2   <=   `DLY 1'b0;
        end
        else
        begin
            gt0_txfsmresetdone_r    <=   `DLY gt0_txfsmresetdone_i;
            gt0_txfsmresetdone_r2   <=   `DLY gt0_txfsmresetdone_r;
        end
    end



    //***********************************************************************//
    //                                                                       //
    //------------------------  Frame Generators  ---------------------------//
    //                                                                       //
    //***********************************************************************//
    // The example design uses Block RAM based frame generators to provide test
    // data to the GTs for transmission. By default the frame generators are 
    // loaded with an incrementing data sequence that includes commas/alignment
    // characters for alignment. If your protocol uses channel bonding, the 
    // frame generator will also be preloaded with a channel bonding sequence.
    
    // You can modify the data transmitted by changing the INIT values of the frame
    // generator in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.


    hv_proto_tx gt0_hv_proto_tx
    (
        .clk                  (gt0_txusrclk2_i),
        .rst                  (gt0_tx_system_reset_c),
        .data_in              (gt0_hv_external_data_i),
        .data_valid           (gt0_hv_external_valid_i),
        .use_internal_source  (1'b1),
        .addr_base            (16'h1000),
        .addr_limit           (16'h11A4),
        .frame_valid_count    (7'd97),
        .packet_out           (gt0_hv_packet_i),
        .packet_valid         (gt0_hv_packet_valid_i),
        .current_addr         (gt0_hv_current_addr_i),
        .using_internal_source(gt0_hv_using_internal_i)
    );

    gtwizard_0_GT_FRAME_GEN #
    (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM)
    )
    gt0_frame_gen
    (
        // User Interface
        .TX_DATA_OUT                    (gt0_frame_gen_data_i),
        .TXCTRL_OUT                     (gt0_frame_gen_ctrl_i),
        .READ_COUNTER_OUT               (gt0_tx_read_counter_i),

        // System Interface
        .USER_CLK                        (gt0_txusrclk2_i),
        .SYSTEM_RESET                   (gt0_tx_system_reset_c)
    );

    assign {gt0_txdata_float_i, gt0_txdata_i, gt0_txdata_float16_i} =
        gt0_hv_packet_valid_i
        ? {gt0_frame_gen_data_i[79:48], gt0_hv_packet_i, gt0_frame_gen_data_i[15:0]}
        : gt0_frame_gen_data_i;

    assign {gt0_txcharisk_float_i, gt0_txcharisk_i} = gt0_frame_gen_ctrl_i;

    //***********************************************************************//
    //                                                                       //
    //------------------------  Frame Checkers  -----------------------------//
    //                                                                       //
    //***********************************************************************//
    // The example design uses Block RAM based frame checkers to verify incoming  
    // data. By default the frame generators are loaded with a data sequence that 
    // matches the outgoing sequence of the frame generators for the TX ports.
    
    // You can modify the expected data sequence by changing the INIT values of the frame
    // checkers in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.
    
    // When the frame checker receives data, it attempts to synchronise to the 
    // incoming pattern by looking for the first sequence in the pattern. Once it 
    // finds the first sequence, it increments through the sequence, and indicates an 
    // error whenever the next value received does not match the expected value.


    assign gt0_frame_check_reset_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?reset_on_data_error_i:gt0_matchn_i;

    // gt0_frame_check0 is always connected to the lane with the start of char 
    // and this lane starts off the data checking on all the other lanes. The INC_IN port is tied off
    assign gt0_inc_in_i = 1'b0;

    gtwizard_0_GT_FRAME_CHECK #
    (
.RX_DATA_WIDTH ( 32 ),
.RXCTRL_WIDTH ( 4 ),
.COMMA_DOUBLE ( 16'h04bc ),
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
.START_OF_PACKET_CHAR ( 32'h060504bc )
    )
    gt0_frame_check
    (
        // GT Interface
        .RX_DATA_IN                     (gt0_rxdata_i),
        .RXCTRL_IN                      (gt0_rxcharisk_i),
        .RXENMCOMMADET_OUT              (gt0_rxmcommaalignen_i),
        .RXENPCOMMADET_OUT              (gt0_rxpcommaalignen_i),
        .RX_ENCHAN_SYNC_OUT             ( ),
        .RX_CHANBOND_SEQ_IN             (tied_to_ground_i),
        // Control Interface
        .INC_IN                         (gt0_inc_in_i),
        .INC_OUT                        (gt0_inc_out_i),
        .PATTERN_MATCHB_OUT             (gt0_matchn_i),
        .RESET_ON_ERROR_IN              (gt0_frame_check_reset_i),
        // System Interface
        .USER_CLK                       (gt0_rxusrclk2_i),
        .SYSTEM_RESET                   (gt0_rx_system_reset_c),
        .ERROR_COUNT_OUT                (gt0_error_count_i),
        .TRACK_DATA_OUT                 (gt0_track_data_i),
        .DEBUG_RX_DATA_ALIGNED_OUT      (gt0_rxdata_aligned_dbg_i),
        .DEBUG_RX_DATA_TRACK_OUT        (gt0_rxdata_track_dbg_i),
        .DEBUG_SEL_OUT                  (gt0_rxalign_sel_dbg_i),
        .DEBUG_START_OF_PACKET_OUT      (gt0_rxstart_of_packet_dbg_i)
    );

    assign gt0_hv_rx_packet_valid_i =
        gt0_rxbyteisaligned_i &&
        !gt0_rx_system_reset_c &&
        (gt0_rxdisperr_i == 4'd0) &&
        (gt0_rxnotintable_i == 4'd0);

    hv_proto_rx_mon gt0_hv_proto_rx_mon
    (
        .clk            (gt0_rxusrclk2_i),
        .rst            (gt0_rx_system_reset_c),
        .packet_in      (gt0_rxdata_track_dbg_i),
        .packet_valid   (gt0_hv_rx_packet_valid_i),
        .addr_base      (16'h1000),
        .addr_limit     (16'h11A4),
        .frame_valid_count(7'd97),
        .packet_out     (gt0_hv_rx_packet_i),
        .current_addr   (gt0_hv_rx_current_addr_i),
        .current_data   (gt0_hv_rx_current_data_i),
        .expected_addr  (gt0_hv_rx_expected_addr_i),
        .packet_seen    (gt0_hv_rx_packet_seen_i),
        .addr_in_range  (gt0_hv_rx_addr_in_range_i),
        .seq_locked     (gt0_hv_rx_seq_locked_i),
        .seq_ok         (gt0_hv_rx_seq_ok_i),
        .invalid_fill   (gt0_hv_rx_invalid_fill_i),
        .seq_error_count(gt0_hv_rx_seq_error_count_i)
    );



    assign TRACK_DATA_OUT = track_data_out_i;

    assign track_data_out_i = 
                                gt0_track_data_i ;









//-------------------------------------------------------------------------------------


//-------------------------Debug Signals assignment--------------------
    assign  gt0_rxlpmen_i                        =  tied_to_vcc_i;

//------------ optional Ports assignments --------------
assign  gt0_rxprbscntreset_i                 =  tied_to_ground_i;
assign  gt0_rxprbssel_i                      =  0;
assign  gt0_loopback_i                       =  0;
assign  gt0_rxuserrdy_i                      =  tied_to_vcc_i;
assign  gt0_gtrxreset_i                      =  tied_to_ground_i;
assign  gt0_rxpcsreset_i                     =  tied_to_ground_i;
 
assign  gt0_txdiffctrl_i                     =  0;
assign  gt0_rxbufreset_i                     =  tied_to_ground_i;
assign  gt0_rxcdrhold_i                      =  tied_to_ground_i;
 //------GTH/GTP
assign  gt0_rxdfelpmreset_i                  =  tied_to_ground_i;
assign  gt0_rxpmareset_i                     =  tied_to_ground_i;
assign  gt0_rxpolarity_i                     =  tied_to_ground_i;
assign  gt0_rxpd_i                           =  0;
assign  gt0_txprecursor_i                    =  0;
assign  gt0_txpostcursor_i                   =  0;
assign  gt0_txinhibit_i                      =  tied_to_ground_i;
assign  gt0_txpolarity_i                     =  tied_to_ground_i;
assign  gt0_txpd_i                           =  0;
assign  gt0_txprbsforceerr_i                 =  tied_to_ground_i;
assign  gt0_txprbssel_i                      =  0;
assign  gt0_txuserrdy_i                      =  tied_to_vcc_i;
assign  gt0_gttxreset_i                      =  tied_to_ground_i;
assign  gt0_txpcsreset_i                     =  tied_to_ground_i;
assign  gt0_txpmareset_i                     =  tied_to_ground_i;
//------------------------------------------------------
    // assign resets for frame_gen modules
    assign  gt0_tx_system_reset_c = !gt0_txfsmresetdone_r2;

    // assign resets for frame_check modules
    assign  gt0_rx_system_reset_c = !gt0_rxresetdone_r3;

assign gt0_drpaddr_i = 9'd0;
assign gt0_drpdi_i = 16'd0;
assign gt0_drpen_i = 1'b0;
assign gt0_drpwe_i = 1'b0;
assign soft_reset_i = tied_to_ground_i;
assign DBG_GT0_CPLLLOCK        = gt0_cplllock_i;
assign DBG_GT0_CPLLFBCLKLOST   = gt0_cpllfbclklost_i;
assign DBG_GT0_TXRESETDONE     = gt0_txresetdone_i;
assign DBG_GT0_TXFSMRESETDONE  = gt0_txfsmresetdone_i;
assign DBG_GT0_TX_SYSTEM_RESET = gt0_tx_system_reset_c;
assign DBG_GT0_TXUSERRDY       = gt0_txuserrdy_i;
assign DBG_GT0_GTTXRESET       = gt0_gttxreset_i;
assign DBG_GT0_TXPMARESET      = gt0_txpmareset_i;
assign DBG_GT0_TXPCSRESET      = gt0_txpcsreset_i;
assign DBG_GT0_TXDATA          = gt0_txdata_i;
assign DBG_GT0_TXCHARISK       = gt0_txcharisk_i;
assign DBG_GT0_TX_READ_COUNTER = gt0_tx_read_counter_i;
assign DBG_GT0_TXUSRCLK2       = gt0_txusrclk2_i;
assign DBG_GT0_RXRESETDONE     = gt0_rxresetdone_i;
assign DBG_GT0_RXFSMRESETDONE  = gt0_rxfsmresetdone_i;
assign DBG_GT0_RX_SYSTEM_RESET = gt0_rx_system_reset_c;
assign DBG_GT0_RXUSERRDY       = gt0_rxuserrdy_i;
assign DBG_GT0_GTRXRESET       = gt0_gtrxreset_i;
assign DBG_GT0_RXPMARESET      = gt0_rxpmareset_i;
assign DBG_GT0_RXPCSRESET      = gt0_rxpcsreset_i;
assign DBG_GT0_RXDATA          = gt0_rxdata_i;
assign DBG_GT0_RXCHARISK       = gt0_rxcharisk_i;
assign DBG_GT0_ERROR_COUNT     = gt0_error_count_i;
assign DBG_GT0_TRACK_DATA      = gt0_track_data_i;
assign DBG_GT0_RXDISPERR       = gt0_rxdisperr_i;
assign DBG_GT0_RXNOTINTABLE    = gt0_rxnotintable_i;
assign DBG_GT0_RXBYTEISALIGNED = gt0_rxbyteisaligned_i;
assign DBG_GT0_RXBYTEREALIGN   = gt0_rxbyterealign_i;
assign DBG_GT0_RXCOMMADET      = gt0_rxcommadet_i;
assign DBG_GT0_RXMCOMMAALIGNEN = gt0_rxmcommaalignen_i;
assign DBG_GT0_RXPCOMMAALIGNEN = gt0_rxpcommaalignen_i;
assign DBG_GT0_RXCLKCORCNT     = gt0_rxclkcorcnt_i;
assign DBG_GT0_RXDATA_ALIGNED  = gt0_rxdata_aligned_dbg_i;
assign DBG_GT0_RXDATA_TRACK    = gt0_rxdata_track_dbg_i;
assign DBG_GT0_RXALIGN_SEL     = gt0_rxalign_sel_dbg_i;
assign DBG_GT0_RXSTART_OF_PACKET = gt0_rxstart_of_packet_dbg_i;
assign DBG_GT0_RXUSRCLK2       = gt0_rxusrclk2_i;
assign DBG_HV_PACKET_OUT       = gt0_hv_packet_i;
assign DBG_HV_CURRENT_ADDR     = gt0_hv_current_addr_i;
assign DBG_HV_PACKET_VALID     = gt0_hv_packet_valid_i;
assign DBG_HV_USING_INTERNAL_SOURCE = gt0_hv_using_internal_i;
assign DBG_HV_RX_PACKET_OUT    = gt0_hv_rx_packet_i;
assign DBG_HV_RX_CURRENT_ADDR  = gt0_hv_rx_current_addr_i;
assign DBG_HV_RX_CURRENT_DATA  = gt0_hv_rx_current_data_i;
assign DBG_HV_RX_EXPECTED_ADDR = gt0_hv_rx_expected_addr_i;
assign DBG_HV_RX_PACKET_SEEN   = gt0_hv_rx_packet_seen_i;
assign DBG_HV_RX_ADDR_IN_RANGE = gt0_hv_rx_addr_in_range_i;
assign DBG_HV_RX_SEQ_LOCKED    = gt0_hv_rx_seq_locked_i;
assign DBG_HV_RX_SEQ_OK        = gt0_hv_rx_seq_ok_i;
assign DBG_HV_RX_INVALID_FILL  = gt0_hv_rx_invalid_fill_i;
assign DBG_HV_RX_SEQ_ERROR_COUNT = gt0_hv_rx_seq_error_count_i;
assign DBG_SOFT_RESET          = soft_reset_i;
assign DBG_DRPCLK_HEARTBEAT    = drpclk_heartbeat_cnt[15];
endmodule
    
