# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/loopback_debug_bd_ila_0_0.xci
# IP: The module: 'loopback_debug_bd_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/loopback_debug_bd_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/loopback_debug_bd_ila_0_0.xci
# IP: The module: 'loopback_debug_bd_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Controler/Controler/Controler.srcs/sources_1/bd/loopback_debug_bd/ip/loopback_debug_bd_ila_0_0/loopback_debug_bd_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'loopback_debug_bd_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
